# Generated by Django 5.1.7 on 2026-07-12 18:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrm', '0061_alter_employee_emp_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='hrm.rdaemployee')),
            ],
            options={
                'ordering': ['dept_id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('unit', models.CharField(choices=[('PCS', 'Pcs'), ('REAM', 'Ream'), ('BOX', 'Box'), ('SET', 'Set'), ('KG', 'Kg'), ('LTR', 'Litre'), ('UNIT', 'Unit')], default='PCS', max_length=10)),
                ('min_stock', models.PositiveIntegerField(default=0)),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_asset', models.BooleanField(default=False, help_text='Tick for returnable assets (furniture, laptop, etc.) that get assigned to an employee instead of being consumed.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='office_inventory.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='office_inventory.location')),
            ],
            options={
                'ordering': ['category', 'item_code'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('RETURNED', 'Returned')], default='ASSIGNED', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_items', to='hrm.rdaemployee')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='office_inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_no', models.CharField(blank=True, max_length=30, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('supplier', models.CharField(blank=True, max_length=150)),
                ('qty', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='ORDERED', max_length=20)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='office_inventory.inventoryitem')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_received', to='hrm.rdaemployee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_no', models.CharField(blank=True, max_length=30, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('requested_qty', models.PositiveIntegerField()),
                ('approved_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('issued_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DEPT_APPROVED', 'Department Approved'), ('DEPT_REJECTED', 'Department Rejected'), ('ADMIN_APPROVED', 'Admin Approved'), ('ADMIN_REJECTED', 'Admin Rejected'), ('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('dept_approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_approved_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_approvals', to='hrm.rdaemployee')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='office_inventory.department')),
                ('dept_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_approvals', to='hrm.rdaemployee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='hrm.rdaemployee')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='office_inventory.inventoryitem')),
                ('store_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_issues', to='hrm.rdaemployee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=5)),
                ('qty_in', models.PositiveIntegerField(default=0)),
                ('qty_out', models.PositiveIntegerField(default=0)),
                ('balance', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='office_inventory.inventoryitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.rdaemployee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
