# Generated by Django 6.0.7 on 2026-07-14 10:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0061_alter_employee_emp_type'),
        ('office_inventory', '0002_simplify_item_master_and_link_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('requires_employee', models.BooleanField(default=True, help_text='Tick if this assign type hands the item to a specific employee. Untick for non-employee targets (restaurant, department, warehouse, etc.) where a free-text name is used instead.')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DamageReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DamageResponsibleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Damage Responsible Type',
                'verbose_name_plural': 'Damage Responsible Types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='assignee_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Where the asset is physically deployed/held.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='office_inventory.location'),
        ),
        migrations.AlterField(
            model_name='employeeassignment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_items', to='hrm.rdaemployee'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='assignment_type',
            field=models.ForeignKey(blank=True, help_text='Who/what this item is assigned to (Employee, Restaurant, Department, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='office_inventory.assignmenttype'),
        ),
        migrations.CreateModel(
            name='DamageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_no', models.CharField(blank=True, max_length=30, unique=True)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('date_reported', models.DateField(default=django.utils.timezone.now)),
                ('responsible_note', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor (repairable)'), ('MAJOR', 'Major (partially usable)'), ('TOTAL_LOSS', 'Total Loss')], default='MINOR', max_length=20)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('WRITTEN_OFF', 'Written Off')], default='REPORTED', max_length=20)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduct_from_stock', models.BooleanField(default=True, help_text='Tick to remove the damaged quantity from current stock immediately.')),
                ('action_taken', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_records', to='office_inventory.employeeassignment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damage_records', to='office_inventory.inventoryitem')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_records', to='office_inventory.location')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damage_records', to='office_inventory.damagereason')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_reports', to='hrm.rdaemployee')),
                ('responsible_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damages_caused', to='hrm.rdaemployee')),
                ('responsible_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damage_records', to='office_inventory.damageresponsibletype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
