# Generated by Django 5.1.7 on 2026-07-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_inventory', '0003_assignment_and_damage_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='type',
            field=models.CharField(choices=[('PCS', 'Pcs'), ('REAM', 'Ream'), ('BOX', 'Box'), ('SET', 'Set'), ('KG', 'Kg'), ('LTR', 'Litre'), ('UNIT', 'Unit')], default='', max_length=10),
        ),
    ]
