# Generated by Django 5.1.7 on 2026-07-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office_inventory', '0004_inventoryitem_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='type',
        ),
    ]
