# Generated by Django 5.1.7 on 2026-07-20 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_inventory', '0005_remove_inventoryitem_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='office_inventory.location'),
        ),
    ]
