# Generated by Django 5.1.7 on 2026-07-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_inventory', '0006_inventoryitem_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
