# Generated by Django 5.1.7 on 2026-07-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_inventory', '0007_alter_inventoryitem_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
