# Generated by Django 5.1.7 on 2026-07-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_inventory', '0008_alter_department_dept_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('PCS', 'Pcs'), ('REAM', 'Ream'), ('BOX', 'Box'), ('SET', 'Set'), ('KG', 'Kg'), ('LTR', 'Litre'), ('UNIT', 'Unit'), ('GRAM', 'Gram')], default='PCS', max_length=10),
        ),
    ]
