# Generated by Django 5.1.7 on 2026-07-29 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_inventory', '0010_restaurant_assignment_and_project_wise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmenttype',
            name='employee_source',
            field=models.CharField(choices=[('NONE', 'No specific employee (free-text name)'), ('HR', 'HR / Office Employee (hrm.RdaEmployee)'), ('RESTAURANT', 'Restaurant Employee (RestaurantEmployee)')], default='HR', help_text="Controls which dropdown the Assign form shows: HR Employee, Restaurant Employee, or plain free-text (e.g. 'Head Office Pool').", max_length=20),
        ),
        migrations.AlterField(
            model_name='assignmenttype',
            name='requires_employee',
            field=models.BooleanField(default=True, help_text='Tick if this assign type hands the item to a specific employee. Untick for non-employee targets (department pool, warehouse, etc.) where a free-text name is used instead. Kept for backward compatibility - `employee_source` below is the more precise control.'),
        ),
        migrations.AlterField(
            model_name='employeeassignment',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Where the asset is physically deployed/held (Head Office, a Restaurant branch, a Kitchen under either, etc.).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='office_inventory.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('HEAD_OFFICE', 'Head Office'), ('RESTAURANT', 'Restaurant'), ('KITCHEN', 'Kitchen'), ('WAREHOUSE', 'Warehouse'), ('OTHER', 'Other')], default='OTHER', help_text='Head Office, Restaurant, Kitchen (under either), Warehouse, or Other.', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="e.g. set this to 'Head Office' or a specific Restaurant to model its Kitchen as a sub-location.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_locations', to='office_inventory.location'),
        ),
    ]
