# Generated by Django 5.1.7 on 2026-08-07 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('office_inventory', '0011_alter_assignmenttype_employee_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='manager',
        ),
        migrations.AddField(
            model_name='department',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='department',
            name='dept_type',
            field=models.CharField(choices=[('btp', 'BTP Office'), ('restaurant', 'Restaurant')], default='btp', max_length=20),
        ),
        migrations.AddField(
            model_name='department',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
