# Generated by Django 5.1.7 on 2025-04-26 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0024_buyer_nid_buyer_photo_alter_buyer_buyer_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boq_cat_type', models.CharField(choices=[('Material Purchase Cost', 'Material Purchase Cost'), ('Labor Cost', 'Labor Cost')], default='General', max_length=100)),
                ('boq_cat_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='Default Project', max_length=200)),
                ('employee_name', models.CharField(max_length=100)),
                ('first_month_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_duration_months', models.IntegerField()),
                ('total_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('yearly_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFirstLevelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_first_name', models.CharField(default='', max_length=255)),
                ('location', models.CharField(default='', max_length=255)),
                ('project_type', models.CharField(choices=[('Own Project', 'Own Project'), ('Joint Venture Project', 'Joint Venture Project'), ('Only Construction Company', 'Only Construction Company')], default='Own Project', max_length=255)),
                ('project_start_month', models.CharField(default='April 2025', max_length=50)),
                ('project_duration', models.PositiveIntegerField(default=12, help_text='Duration in months')),
                ('project_size_sq_ft', models.PositiveIntegerField(default=1000)),
                ('number_of_units', models.PositiveIntegerField(default=1)),
                ('number_of_floors', models.PositiveIntegerField(default=1)),
                ('units_per_floor', models.PositiveIntegerField(default=1)),
                ('soil_test_completed', models.BooleanField(default=False)),
                ('drawing_test_completed', models.BooleanField(default=False)),
                ('agreement_completed', models.BooleanField(default=False)),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('soil_test', models.FileField(blank=True, null=True, upload_to='soil_documents/')),
                ('drawing_test', models.FileField(blank=True, null=True, upload_to='drawing_documents/')),
                ('agreement_document', models.FileField(blank=True, null=True, upload_to='agreement_documents/')),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('percentage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_total_with_extra', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('project_start_date', models.DateField(blank=True, null=True)),
                ('project_end_date', models.DateField(blank=True, null=True)),
                ('project_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertyowner')),
            ],
        ),
        migrations.CreateModel(
            name='BOQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('Material Purchase Cost', 'Material Purchase Cost'), ('Labor Cost', 'Labor Cost')], default='Material Purchase Cost', max_length=100)),
                ('category_name', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('qty', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname')),
                ('supplier_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.suppliers')),
            ],
        ),
    ]
