# Generated by Django 5.1.7 on 2025-04-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesupervisor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contructor/'),
        ),
    ]
