# Generated by Django 5.1.7 on 2025-04-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_sitesupervisor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesupervisor',
            name='image',
            field=models.ImageField(blank=True, upload_to='contructor/'),
        ),
    ]
