# Generated by Django 5.1.7 on 2025-04-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_sitesupervisor_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesupervisor',
            old_name='image',
            new_name='photo',
        ),
    ]
