# Generated by Django 5.1.7 on 2025-04-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_image_sitesupervisor_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesupervisor',
            name='photo',
        ),
    ]
