# Generated by Django 5.1.7 on 2025-04-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_sitesupervisor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
