# Generated by Django 5.1.7 on 2025-04-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_suppliers_active_suppliers_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boq',
            name='qty',
            field=models.FloatField(),
        ),
    ]
