# Generated by Django 5.1.7 on 2025-04-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_boq_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boq',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
