# Generated by Django 5.1.7 on 2025-04-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_boq_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boq',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='boq',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='boq',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
