# Generated by Django 5.1.7 on 2025-05-07 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfirstlevelname',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectlocation'),
        ),
    ]
