# Generated by Django 5.1.7 on 2025-05-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_projectfirstlevelname_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfirstlevelname',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
