# Generated by Django 5.1.7 on 2025-05-07 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_projectfirstlevelname_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfirstlevelname',
            name='location',
        ),
    ]
