# Generated by Django 5.1.7 on 2025-05-07 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_remove_projectfirstlevelname_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfirstlevelname',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectlocation'),
        ),
    ]
