# Generated by Django 4.2.20 on 2025-06-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_projectfirstlevelname_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='boq',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boq',
            name='status_item',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='boq',
            name='update_item',
            field=models.CharField(default='', max_length=100),
        ),
    ]
