# Generated by Django 4.2.20 on 2025-06-25 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_boq_remark_boq_status_item_boq_update_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoRevisedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_new_entry', models.BooleanField(default=False)),
                ('linked_boq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revised_entries', to='projects.boq')),
                ('original_boq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.boq')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname')),
                ('supplier_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.suppliers')),
            ],
        ),
    ]
