# Generated by Django 4.2.20 on 2025-06-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_boreviseditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqcategory',
            name='boq_cat_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='boqcategory',
            name='boq_cat_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
