# Generated by Django 4.2.20 on 2025-06-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_boqcategory_boq_cat_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boq',
            name='boq_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
