# Generated by Django 4.2.20 on 2025-07-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_boq_boq_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoQType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boq_type_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='boq',
            name='type_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
