# Generated by Django 4.2.20 on 2025-07-05 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_boqtype_boq_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_head', models.CharField(help_text='E.g., Basement, Piling, First Floor', max_length=100)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('work_start_date', models.DateField()),
                ('work_end_date', models.DateField()),
                ('work_description', models.TextField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('paused', 'Paused')], default='ongoing', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.sitesupervisor')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname')),
            ],
        ),
    ]
