# Generated by Django 4.2.20 on 2025-07-15 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_contractoractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('party', models.CharField(choices=[('BTP Office', 'BTP Office'), ('Client', 'Client')], max_length=20)),
                ('sl', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('band', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('amount', models.FloatField(blank=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname')),
            ],
        ),
    ]
