# Generated by Django 4.2.20 on 2025-10-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_sitesupervisor_pay_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boq',
            name='category_type',
            field=models.CharField(choices=[('Materials Purchase Cost', 'Materials Purchase Cost'), ('Labour Cost', 'Labour Cost')], default='Materials Purchase Cost', max_length=100),
        ),
    ]
