# Generated by Django 5.1.7 on 2026-01-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
