# Generated by Django 5.1.7 on 2026-01-12 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_donation_donation_type_alter_donation_donation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.donationtype'),
        ),
    ]
