# Generated by Django 5.1.7 on 2026-01-27 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_alter_donation_donation_type_delete_donationtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donation_type',
        ),
    ]
