# Generated by Django 5.1.7 on 2026-08-28 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_remove_donation_donation_type'),
        ('purchase', '0065_billrequisitionapprovalpayment_requi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boq',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.headofrequisition'),
        ),
    ]
