# Generated by Django 5.1.7 on 2026-08-28 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_alter_boq_item_name'),
        ('purchase', '0065_billrequisitionapprovalpayment_requi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boreviseditem',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.headofrequisition'),
        ),
    ]
