# Generated by Django 5.1.7 on 2026-09-20 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_alter_boreviseditem_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('agreement', 'Agreement / Land Papers'), ('test', 'Test'), ('drawing', 'Drawing'), ('certification', 'Certification'), ('approval', 'Approvals')], max_length=50)),
                ('document', models.FileField(upload_to='project_documents/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_documents', to='projects.projectfirstlevelname')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_structure', models.PositiveIntegerField(default=0, help_text='Duration in months')),
                ('super_structure', models.PositiveIntegerField(default=0, help_text='Duration in months')),
                ('finishing', models.PositiveIntegerField(default=0, help_text='Duration in months')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_schedule', to='projects.projectfirstlevelname')),
            ],
        ),
    ]
