# Generated by Django 5.0 on 2026-09-21 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_projectdocument_projectschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('schedule_type', models.CharField(choices=[('sub_structure', 'Sub Structure'), ('super_structure', 'Super Structure'), ('finishing', 'Finishing')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='projects.projectfirstlevelname')),
            ],
        ),
    ]
