# Generated by Django 5.0 on 2026-09-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_projectscheduleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectscheduleitem',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectscheduleitem',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
