# Generated by Django 4.2.20 on 2025-09-22 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0024_materialentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rda_emp_name', models.CharField(max_length=100)),
                ('rda_emp_type', models.CharField(max_length=20)),
                ('rda_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rda_phone', models.CharField(max_length=50)),
                ('rda_email', models.EmailField(max_length=254)),
                ('rda_position', models.CharField(max_length=100)),
                ('rda_address', models.TextField()),
                ('rda_nid', models.CharField(default='', max_length=100)),
                ('rda_dofb', models.CharField(default='', max_length=100)),
                ('rda_active_status', models.BooleanField(default=True)),
                ('rda_photo', models.ImageField(blank=True, null=True, upload_to='rda_emp_photos/')),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfirstlevelname')),
            ],
        ),
    ]
