# Generated by Django 4.2.20 on 2025-09-23 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0004_restaurantadvancepayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantAdvancePayment',
        ),
    ]
