# Generated by Django 4.2.20 on 2025-09-23 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0006_restaurantadvancepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantadvancepayment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restahrm.restaurantemployee'),
        ),
    ]
