# Generated by Django 4.2.20 on 2025-09-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0007_alter_restaurantadvancepayment_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantemployee',
            name='rda_emp_shift',
            field=models.CharField(default='Morning', max_length=50),
        ),
    ]
