# Generated by Django 4.2.20 on 2025-09-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0008_restaurantemployee_rda_emp_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantemployee',
            name='rda_emp_shift',
        ),
        migrations.AddField(
            model_name='restaurantattendance',
            name='emp_shift',
            field=models.CharField(default='Morning', max_length=50),
        ),
    ]
