# Generated by Django 5.1.7 on 2025-11-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0010_restaurantallowances_restaurantleave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantShiftSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('night', 'Night')], max_length=50, unique=True, verbose_name='Shift Name')),
                ('checkin_time', models.TimeField(verbose_name='Check-in Time')),
                ('checkout_time', models.TimeField(verbose_name='Check-out Time')),
            ],
            options={
                'verbose_name': 'Restaurant Shift Schedule',
                'verbose_name_plural': 'Restaurant Shift Schedules',
                'ordering': ['shift_name'],
            },
        ),
    ]
