# Generated by Django 5.1.7 on 2025-11-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0011_restaurantshiftschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantemployee',
            name='rda_shift',
            field=models.CharField(default='Morning', max_length=50),
        ),
    ]
