# Generated by Django 5.1.7 on 2025-12-07 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0012_restaurantemployee_rda_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantemployee',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restahrm.restaurantemployee'),
        ),
    ]
