# Generated by Django 5.1.7 on 2025-12-07 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_alter_boq_category_type'),
        ('restahrm', '0013_alter_restaurantemployee_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantemployee',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfirstlevelname'),
        ),
    ]
