# Generated by Django 5.1.7 on 2026-01-06 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0014_alter_restaurantemployee_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantIom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restahrm.restaurantemployee')),
            ],
        ),
    ]
