# Generated by Django 5.1.7 on 2026-01-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0015_restaurantiom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantIom',
        ),
    ]
