# Generated by Django 5.1.7 on 2026-02-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0017_restaurantiom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantiom',
            name='employee',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
