# Generated by Django 5.1.7 on 2026-02-01 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0018_alter_restaurantiom_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantiom',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restahrm.restaurantemployee'),
        ),
    ]
