# Generated by Django 5.1.7 on 2026-02-01 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0019_alter_restaurantiom_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestaurantIom',
            new_name='RestIom',
        ),
    ]
