# Generated by Django 5.1.7 on 2026-02-01 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0022_iomrestaurant_delete_restiom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IOMRestaurant',
            new_name='RestIom',
        ),
    ]
