# Generated by Django 5.1.7 on 2026-02-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0023_rename_iomrestaurant_restiom'),
    ]

    operations = [
        migrations.AddField(
            model_name='restiom',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
