# Generated by Django 5.1.7 on 2026-02-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0024_restiom_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restiom',
            name='end_date',
            field=models.DateField(),
        ),
    ]
