# Generated by Django 5.1.7 on 2026-02-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0025_alter_restiom_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='restiom',
            name='device_sn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
