# Generated by Django 5.1.7 on 2026-02-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0029_alter_restiom_device_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantleave',
            name='device_sn',
            field=models.CharField(choices=[('SMR5253000079', 'SMR5253000079-Cafe'), ('SMR5253000181', 'SMR5253000181-Live')], default='SMR5253000079', max_length=20),
        ),
    ]
