# Generated by Django 5.1.7 on 2026-02-02 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0015_restmainchequebook_restmaincheque'),
        ('restahrm', '0030_restaurantleave_device_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantadvancepayment',
            name='cash_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaccounting.cashresttype'),
        ),
    ]
