# Generated by Django 5.1.7 on 2026-02-02 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0015_restmainchequebook_restmaincheque'),
        ('restahrm', '0031_alter_restaurantadvancepayment_cash_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantallowances',
            name='cash_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaccounting.cashresttype'),
        ),
        migrations.AlterField(
            model_name='restaurantloanpayment',
            name='cash_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaccounting.cashresttype'),
        ),
        migrations.AlterField(
            model_name='restaurantsalarypayment',
            name='cash_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaccounting.cashresttype'),
        ),
    ]
