# Generated by Django 5.1.7 on 2026-02-03 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0015_restmainchequebook_restmaincheque'),
        ('restahrm', '0032_alter_restaurantallowances_cash_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantadvancepayment',
            name='debit_voucher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaccounting.debitrestvoucher'),
        ),
    ]
