# Generated by Django 5.1.7 on 2026-02-07 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0015_restmainchequebook_restmaincheque'),
        ('restahrm', '0033_restaurantadvancepayment_debit_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantadvancepayment',
            name='head_of_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaccounting.restheadofaccount'),
        ),
        migrations.AlterField(
            model_name='restaurantallowances',
            name='head_of_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaccounting.restheadofaccount'),
        ),
        migrations.AlterField(
            model_name='restaurantloanpayment',
            name='head_of_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaccounting.restheadofaccount'),
        ),
        migrations.AlterField(
            model_name='restaurantsalarypayment',
            name='head_of_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaccounting.restheadofaccount'),
        ),
    ]
