# Generated by Django 5.1.7 on 2026-02-17 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0035_restaurantfoodbillpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantFoodBillPayment',
        ),
    ]
