# Generated by Django 5.1.7 on 2026-02-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0036_delete_restaurantfoodbillpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantadvancepayment',
            name='payment_status',
            field=models.CharField(choices=[('advance', 'Advance Payment'), ('foodbill', 'Food Bill')], default='Advance Payment', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurantadvancepayment',
            name='status',
            field=models.CharField(default='due', max_length=10),
        ),
    ]
