# Generated by Django 5.1.7 on 2026-02-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0037_restaurantadvancepayment_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantadvancepayment',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='restaurantadvancepayment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('due', 'Due')], default='due', max_length=10),
        ),
    ]
