# Generated by Django 5.1.7 on 2026-02-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0039_restaurantfoodbillpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantFoodBillPayment',
        ),
    ]
