# Generated by Django 5.1.7 on 2026-02-21 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_remove_donation_donation_type'),
        ('restaccounting', '0019_delete_restfoodbillvoucher'),
        ('restahrm', '0040_delete_restaurantfoodbillpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantFoodBillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('monthofsalary', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('cash_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaccounting.cashresttype')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restahrm.restaurantemployee')),
                ('head_of_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaccounting.restheadofaccount')),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfirstlevelname')),
            ],
        ),
    ]
