# Generated by Django 5.1.7 on 2026-02-22 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_bulksms_recipients_bulksmsrecipient'),
        ('restahrm', '0041_restaurantfoodbillpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantfoodbillpayment',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer'),
        ),
        migrations.AddField(
            model_name='restaurantfoodbillpayment',
            name='customer_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Employee', 'Employee')], default='', max_length=20),
        ),
    ]
