# Generated by Django 5.1.7 on 2026-02-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0042_restaurantfoodbillpayment_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantfoodbillpayment',
            name='customer_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Employee', 'Employee')], max_length=20),
        ),
    ]
