# Generated by Django 5.1.7 on 2026-05-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0043_alter_restaurantfoodbillpayment_customer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantallowances',
            name='cash_type',
        ),
        migrations.RemoveField(
            model_name='restaurantallowances',
            name='cheque_number',
        ),
        migrations.RemoveField(
            model_name='restaurantallowances',
            name='head_of_account',
        ),
    ]
