# Generated by Django 5.1.7 on 2026-07-13 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0044_remove_restaurantallowances_cash_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantAttendanceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_info', to='restahrm.restaurantattendance')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_restaurant_attendance_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_verify_restaurant_attendance_location', 'Can verify Restaurant attendance location')],
            },
        ),
    ]
