# Generated by Django 5.1.7 on 2026-07-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0045_restaurantattendancelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantAttendanceAccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Restaurant Attendance Access', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_employees', models.ManyToManyField(blank=True, related_name='attendance_allowed', to='restahrm.restaurantemployee')),
            ],
        ),
    ]
