# Generated by Django 5.1.7 on 2026-07-22 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0046_restaurantattendanceaccesscontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantleave',
            name='handover_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_handover_tasks', to='restahrm.restaurantemployee'),
        ),
        migrations.AddField(
            model_name='restaurantleave',
            name='leave_type',
            field=models.CharField(choices=[('CL', 'Casual Leave (CL)'), ('SL', 'Sick Leave (SL)'), ('EL', 'Earned Leave (EL)'), ('LOP', 'Loss of Pay (LOP)')], default='CL', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurantleave',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='leave_docs/'),
        ),
        migrations.CreateModel(
            name='RestaurantLeaveAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2026)),
                ('casual_leave_allocated', models.FloatField(default=10.0)),
                ('casual_leave_used', models.FloatField(default=0.0)),
                ('sick_leave_allocated', models.FloatField(default=10.0)),
                ('sick_leave_used', models.FloatField(default=0.0)),
                ('earned_leave_allocated', models.FloatField(default=15.0)),
                ('earned_leave_carried_forward', models.FloatField(default=0.0)),
                ('earned_leave_used', models.FloatField(default=0.0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_allocations', to='restahrm.restaurantemployee')),
            ],
            options={
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
