# Generated by Django 4.2.20 on 2025-09-29 17:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0025_sitesupervisor_pay_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('flat', models.CharField(max_length=10)),
                ('varatiya_name', models.CharField(blank=True, max_length=255, null=True)),
                ('core_room_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_rent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('other_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bill_month', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('Generated', 'Generated'), ('Admin Approved', 'Admin Approved'), ('Partial Payment', 'Partial Payment'), ('Payment Clear', 'Payment Clear')], default='Generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('flat', models.CharField(max_length=10)),
                ('varatiya_name', models.CharField(blank=True, max_length=255, null=True)),
                ('electricity_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill_month', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('Generated', 'Generated'), ('Admin Approved', 'Admin Approved'), ('Partial Payment', 'Partial Payment'), ('Payment Clear', 'Payment Clear')], default='Generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GasBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('flat', models.CharField(max_length=10)),
                ('varatiya_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gas_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill_month', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('Generated', 'Generated'), ('Admin Approved', 'Admin Approved'), ('Partial Payment', 'Partial Payment'), ('Payment Clear', 'Payment Clear')], default='Generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('flat', models.CharField(max_length=10)),
                ('varatiya_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parking_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill_month', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('Generated', 'Generated'), ('Admin Approved', 'Admin Approved'), ('Partial Payment', 'Partial Payment'), ('Payment Clear', 'Payment Clear')], default='Generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_names', to='projects.projectfirstlevelname')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startmonths', models.DateField(blank=True, null=True)),
                ('endmonths', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive'), ('Warning', 'Warning')], default='Active', max_length=20)),
                ('projectref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='tenant.projectname')),
            ],
        ),
        migrations.CreateModel(
            name='TenantCashType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('bank', 'Bank Account'), ('mobile', 'Mobile Banking'), ('cash', 'Cash in Hand'), ('other', 'Other')], max_length=20)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Varatiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tenant/varatiya_images/')),
                ('nid', models.ImageField(blank=True, null=True, upload_to='tenant/varatiya_nid_images/')),
                ('contact', models.CharField(max_length=20, unique=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_address', models.TextField()),
                ('number_of_members', models.PositiveIntegerField(default=1)),
                ('reference_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('head_of_account', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('flat', models.CharField(max_length=10)),
                ('varatiya_name', models.CharField(blank=True, max_length=255, null=True)),
                ('water_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill_month', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('Generated', 'Generated'), ('Admin Approved', 'Admin Approved'), ('Partial Payment', 'Partial Payment'), ('Payment Clear', 'Payment Clear')], default='Generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_bills', to='tenant.rent')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('flat', models.CharField(max_length=10)),
                ('varatiya_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill_month', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('Generated', 'Generated'), ('Admin Approved', 'Admin Approved'), ('Partial Payment', 'Partial Payment'), ('Payment Clear', 'Payment Clear')], default='Generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_bills', to='tenant.rent')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('flat', models.CharField(choices=[('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('F4', 'F4'), ('F5', 'F5'), ('F6', 'F6'), ('F7', 'F7'), ('F8', 'F8'), ('F9', 'F9'), ('F10', 'F10'), ('F11', 'F11'), ('F12', 'F12'), ('F13', 'F13'), ('F14', 'F14'), ('F15', 'F15')], max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive'), ('Warning', 'Warning')], default='Deactive', max_length=10)),
                ('core_room_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parking_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gas_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('water_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('electricity_rent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('other_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('meter_number', models.CharField(blank=True, max_length=50, null=True)),
                ('opening_reading', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('last_month_reading', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('unit_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='tenant.varatiya')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='projects.projectfirstlevelname')),
            ],
        ),
        migrations.AddField(
            model_name='rent',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rents', to='tenant.room'),
        ),
        migrations.AddField(
            model_name='rent',
            name='varatiya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rents', to='tenant.varatiya'),
        ),
        migrations.CreateModel(
            name='ReceiveVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(editable=False, max_length=100)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_date', models.DateField(auto_now_add=True, null=True)),
                ('head_of_account', models.CharField(editable=False, max_length=100)),
                ('mr_or_bill_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('generated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('particulars', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('approval_rv_status', models.BooleanField(default=False)),
                ('carrier', models.CharField(blank=True, max_length=255, null=True)),
                ('cash_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.tenantcashtype')),
                ('electricity_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receive_vouchers', to='tenant.electricitybill')),
                ('gas_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receive_vouchers', to='tenant.gasbill')),
                ('parking_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receive_vouchers', to='tenant.parkingbill')),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfirstlevelname')),
                ('rent_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receive_vouchers', to='tenant.bill')),
                ('service_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receive_vouchers', to='tenant.servicebill')),
                ('tenant_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.varatiya')),
                ('water_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receive_vouchers', to='tenant.waterbill')),
            ],
        ),
        migrations.AddField(
            model_name='parkingbill',
            name='rent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_bills', to='tenant.rent'),
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_month', models.DateField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=255)),
                ('bill_no', models.CharField(blank=True, max_length=50, null=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_opening', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='tenant.varatiya')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='gasbill',
            name='rent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gas_bills', to='tenant.rent'),
        ),
        migrations.AddField(
            model_name='electricitybill',
            name='rent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electricity_bills', to='tenant.rent'),
        ),
        migrations.AddField(
            model_name='bill',
            name='rent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='tenant.rent'),
        ),
    ]
