# Generated by Django 4.2.20 on 2025-10-01 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_sitesupervisor_pay_amount_and_more'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectname',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_names', to='projects.projectfirstlevelname'),
        ),
        migrations.AlterField(
            model_name='receivevoucher',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.projectname'),
        ),
        migrations.AlterField(
            model_name='room',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='tenant.projectname'),
        ),
    ]
