# Generated by Django 4.2.20 on 2025-10-03 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_alter_projectname_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitybill',
            name='used_units',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='receive_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='tenant.receivevoucher'),
        ),
    ]
