# Generated by Django 4.2.20 on 2025-10-05 06:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_electricitybill_used_units_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('adjusted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('varatiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='tenant.varatiya')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(editable=False, max_length=100)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_date', models.DateField(auto_now_add=True, null=True)),
                ('head_of_account', models.CharField(editable=False, max_length=100)),
                ('pv_or_bill_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('particulars', models.TextField()),
                ('approval_pv_status', models.BooleanField(default=False)),
                ('carrier', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.tenantcashtype')),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.projectname')),
                ('tenant_advance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers', to='tenant.tenantadvance')),
                ('tenant_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.varatiya')),
            ],
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='payment_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='tenant.paymentvoucher'),
        ),
        migrations.AddField(
            model_name='receivevoucher',
            name='tenant_advance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receive_vouchers', to='tenant.tenantadvance'),
        ),
    ]
