# Generated by Django 4.2.20 on 2025-10-09 04:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_tenantadvance_paymentvoucher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('flat', models.CharField(max_length=10)),
                ('varatiya_name', models.CharField(blank=True, max_length=255, null=True)),
                ('garbage_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill_month', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('Generated', 'Generated'), ('Admin Approved', 'Admin Approved'), ('Partial Payment', 'Partial Payment'), ('Payment Clear', 'Payment Clear')], default='Generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garbage_bills', to='tenant.rent')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='garbage_rent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='MainBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(default=datetime.date.today)),
                ('generated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adjusted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Generated', 'Generated'), ('Approved', 'Approved'), ('Partial Payment', 'Partial Payment'), ('Payment Clear', 'Payment Clear')], default='Generated', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('electricity_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.electricitybill')),
                ('garbage_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.garbagebill')),
                ('gas_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.gasbill')),
                ('parking_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.parkingbill')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.projectname')),
                ('rent_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.bill')),
                ('service_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.servicebill')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.varatiya')),
                ('water_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.waterbill')),
            ],
        ),
        migrations.AddField(
            model_name='receivevoucher',
            name='mainbill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_bill', to='tenant.mainbill'),
        ),
    ]
