# Generated by Django 4.2.20 on 2025-10-14 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_garbagebill_room_garbage_rent_mainbill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_number', models.CharField(max_length=50, unique=True)),
                ('start_number', models.PositiveIntegerField()),
                ('end_number', models.PositiveIntegerField()),
                ('total_cheques', models.PositiveIntegerField(blank=True, null=True)),
                ('issue_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_books', to='tenant.tenantcashtype')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('payee_name', models.CharField(blank=True, max_length=150, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('unused', 'Unused'), ('used', 'Used'), ('issued', 'Issued'), ('discount', 'Discount'), ('cleared', 'Cleared'), ('cancelled', 'Cancelled')], default='unused', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cheque_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='tenant.chequebook')),
            ],
            options={
                'ordering': ['cheque_number'],
            },
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='cheque_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers', to='tenant.cheque'),
        ),
        migrations.AlterField(
            model_name='receivevoucher',
            name='cheque_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receive_vouchers', to='tenant.cheque'),
        ),
    ]
