# Generated by Django 5.1.7 on 2025-10-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_chequebook_cheque_alter_paymentvoucher_cheque_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('punch_time', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('check_type', models.IntegerField()),
                ('field1', models.IntegerField(default=0)),
                ('field2', models.IntegerField(default=0)),
                ('field3', models.IntegerField(default=0)),
                ('field4', models.IntegerField(default=0)),
                ('field5', models.IntegerField(default=0)),
                ('field6', models.IntegerField(default=0)),
                ('device_sn', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
