# Generated by Django 5.1.7 on 2026-02-28 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0007_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBulkSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenantBulkSMSRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(default='Sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('bulk_sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='tenant.tenantbulksms')),
            ],
        ),
    ]
