# Generated by Django 5.1.7 on 2026-02-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0008_tenantbulksms_tenantbulksmsrecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantbulksmsrecipient',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
