# Generated by Django 5.1.7 on 2026-03-08 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0011_ledgerentry_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='tenant.varatiya'),
        ),
    ]
