# Generated by Django 5.1.7 on 2026-03-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0012_alter_ledgerentry_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivevoucher',
            name='bill_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
