# Generated by Django 5.1.7 on 2025-05-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headofrequisition',
            name='head_requi_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
