# Generated by Django 5.1.7 on 2025-05-20 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0008_alter_employee_emp_type'),
        ('projects', '0017_projectfirstlevelname_location'),
        ('purchase', '0002_alter_headofrequisition_head_requi_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionComparative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100)),
                ('qty', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('approv_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approv_note', models.TextField(blank=True, null=True)),
                ('return_requisition', models.CharField(blank=True, max_length=100, null=True)),
                ('requisition_date', models.DateField(blank=True, null=True)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.employee')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.headofrequisition')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname')),
                ('vendor_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.suppliers')),
            ],
        ),
    ]
