# Generated by Django 5.1.7 on 2025-05-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_headofrequisition_head_requi_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadOfExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_exp_name', models.CharField(max_length=255)),
                ('head_exp_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
    ]
