# Generated by Django 5.1.7 on 2025-05-30 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_creditvoucher_bill_date'),
        ('crm', '0001_initial'),
        ('purchase', '0006_expensevoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensevoucher',
            name='bankName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Expense_vouchers_as_bank', to='accounting.cashtype'),
        ),
        migrations.AddField(
            model_name='expensevoucher',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer'),
        ),
        migrations.AddField(
            model_name='expensevoucher',
            name='expense_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.headofexpense'),
        ),
        migrations.AddField(
            model_name='expensevoucher',
            name='type_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expensevoucher',
            name='cash_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Expense_vouchers_as_cash', to='accounting.cashtype'),
        ),
        migrations.AlterField(
            model_name='expensevoucher',
            name='type',
            field=models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor'), ('Customer', 'Customer'), ('Bank', 'Bank')], default='', max_length=20),
        ),
    ]
