# Generated by Django 5.1.7 on 2025-05-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_expensevoucher_bankname_expensevoucher_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensevoucher',
            name='type',
            field=models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor'), ('Customer', 'Customer'), ('Bank', 'Bank'), ('Expense', 'Expense')], default='', max_length=20),
        ),
    ]
