# Generated by Django 5.1.7 on 2025-05-30 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_creditvoucher_bill_date'),
        ('purchase', '0008_alter_expensevoucher_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensevoucher',
            name='bankName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Expense_vouchers_as_bank', to='accounting.cashtype'),
        ),
    ]
