# Generated by Django 5.1.7 on 2025-05-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_alter_expensevoucher_bankname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensevoucher',
            name='approval_dr_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
