# Generated by Django 5.1.7 on 2025-05-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_alter_expensevoucher_approval_dr_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensevoucher',
            name='approval_dr_status',
        ),
        migrations.AddField(
            model_name='expensevoucher',
            name='approv_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensevoucher',
            name='approv_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
