# Generated by Django 5.1.7 on 2025-05-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_remove_expensevoucher_approval_dr_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensevoucher',
            name='requi_id',
        ),
    ]
