# Generated by Django 5.1.7 on 2025-05-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_remove_expensevoucher_requi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensevoucher',
            name='requi_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
