# Generated by Django 5.1.7 on 2025-05-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_expensevoucher_requi_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensevoucher',
            name='requi_id',
        ),
    ]
