# Generated by Django 4.2.20 on 2025-06-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_remove_expensevoucher_requi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='requisitioncomparative',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
