# Generated by Django 4.2.20 on 2025-06-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_alter_requisition_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='requi_uniq_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
