# Generated by Django 4.2.20 on 2025-06-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0016_requisition_requi_uniq_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
