# Generated by Django 4.2.20 on 2025-06-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0017_requisition_type_alter_requisition_vendor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='purch_appov',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
