# Generated by Django 4.2.20 on 2025-06-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0018_requisition_purch_appov'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='purch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='return_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='requisition',
            name='return_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
