# Generated by Django 4.2.20 on 2025-06-30 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0027_advancepayment_cheque_number'),
        ('projects', '0021_boq_boq_date'),
        ('purchase', '0019_requisition_purch_date_requisition_return_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('approv_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approv_note', models.TextField(blank=True, null=True)),
                ('approv_acct_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approv_acct_note', models.TextField(blank=True, null=True)),
                ('approv_purch_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approv_purch_note', models.TextField(blank=True, null=True)),
                ('requisition_date', models.DateField(blank=True, null=True)),
                ('requi_uniq_id', models.IntegerField(blank=True, null=True)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.employee')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.headofrequisition')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname')),
            ],
        ),
    ]
