# Generated by Django 4.2.20 on 2025-07-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0020_pettycash'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='cash_empl',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
