# Generated by Django 4.2.20 on 2025-07-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0021_requisition_cash_empl'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='purch_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
