# Generated by Django 4.2.20 on 2025-07-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0023_expenserequisition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenserequisition',
            old_name='unit',
            new_name='descript',
        ),
        migrations.RemoveField(
            model_name='expenserequisition',
            name='vendor_name',
        ),
    ]
