# Generated by Django 4.2.20 on 2025-07-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0024_rename_unit_expenserequisition_descript_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenserequisition',
            name='type',
        ),
    ]
