# Generated by Django 4.2.20 on 2025-07-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0025_remove_expenserequisition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequisition',
            name='requi_expense_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
