# Generated by Django 4.2.20 on 2025-07-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0026_expenserequisition_requi_expense_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequisition',
            name='requisition_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
