# Generated by Django 4.2.20 on 2025-07-19 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0027_expenserequisition_requisition_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserequisition',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.headofexpense'),
        ),
    ]
