# Generated by Django 4.2.20 on 2025-07-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0028_alter_expenserequisition_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserequisition',
            name='requisition_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
