# Generated by Django 4.2.20 on 2025-07-19 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0030_alter_expenserequisition_requisition_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensevoucher',
            name='bill_date',
        ),
        migrations.RemoveField(
            model_name='expensevoucher',
            name='bill_phase',
        ),
        migrations.RemoveField(
            model_name='expensevoucher',
            name='mr_or_bill_no',
        ),
    ]
