# Generated by Django 4.2.20 on 2025-07-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0031_remove_expensevoucher_bill_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensevoucher',
            name='mr_or_bill_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
