# Generated by Django 4.2.20 on 2025-08-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0032_expensevoucher_mr_or_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequisition',
            name='ledger_add',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
