# Generated by Django 4.2.20 on 2025-08-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0033_expenserequisition_ledger_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='qty',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='rate',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
