# Generated by Django 4.2.20 on 2025-08-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0034_alter_requisition_qty_alter_requisition_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
