# Generated by Django 4.2.20 on 2025-08-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0035_alter_requisition_qty_alter_requisition_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
