# Generated by Django 4.2.20 on 2025-08-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0037_billrequisition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billrequisition',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='billrequisition',
            name='unit',
        ),
    ]
