# Generated by Django 4.2.20 on 2025-08-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0038_remove_billrequisition_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billrequisition',
            name='item_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='billrequisition',
            name='unit',
            field=models.CharField(default='', max_length=50),
        ),
    ]
