# Generated by Django 4.2.20 on 2025-08-27 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0039_billrequisition_item_name_billrequisition_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billrequisition',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.headofrequisition'),
        ),
    ]
