# Generated by Django 4.2.20 on 2025-08-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0040_alter_billrequisition_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='billrequisition',
            name='note',
            field=models.CharField(default='', max_length=50),
        ),
    ]
