# Generated by Django 4.2.20 on 2025-08-27 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0067_alter_debitvoucher_type'),
        ('purchase', '0041_billrequisition_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='billrequisition',
            name='head_of_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.headofaccount'),
        ),
        migrations.AddField(
            model_name='billrequisition',
            name='mr_or_bill_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
