# Generated by Django 4.2.20 on 2025-09-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0042_billrequisition_head_of_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
    ]
