# Generated by Django 4.2.20 on 2025-10-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0043_requisition_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
