# Generated by Django 4.2.20 on 2025-10-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0044_alter_requisition_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
