# Generated by Django 4.2.20 on 2025-10-06 09:10

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_alter_boq_category_type'),
        ('purchase', '0047_alter_requisition_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionApprovalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requi_uniq_id', models.CharField(max_length=50, verbose_name='Requisition Unique ID')),
                ('payment_type', models.CharField(default='requisition_pay', max_length=50)),
                ('requi_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_payments', to='purchase.requisition')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.suppliers')),
            ],
        ),
    ]
