# Generated by Django 4.2.20 on 2025-10-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0048_requisitionapprovalpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionapprovalpayment',
            name='requisition_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
