# Generated by Django 4.2.20 on 2025-10-06 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0049_requisitionapprovalpayment_requisition_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionapprovalpayment',
            name='requi_item_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.headofrequisition'),
        ),
    ]
