# Generated by Django 4.2.20 on 2025-10-07 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0073_transactionhistory_particulars'),
        ('purchase', '0050_requisitionapprovalpayment_requi_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionapprovalpayment',
            name='debit_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.debitvoucher'),
        ),
    ]
