# Generated by Django 4.2.20 on 2025-10-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0051_requisitionapprovalpayment_debit_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionapprovalpayment',
            name='requi_uniq_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Requisition Unique ID'),
        ),
    ]
