# Generated by Django 4.2.20 on 2025-10-12 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0052_alter_requisitionapprovalpayment_requi_uniq_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionapprovalpayment',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_payments', to='purchase.requisition'),
        ),
    ]
