# Generated by Django 5.1.7 on 2025-10-31 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0081_alter_ledgerentry_type'),
        ('purchase', '0053_alter_requisitionapprovalpayment_requisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequisition',
            name='cash_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.cashtype'),
        ),
        migrations.AddField(
            model_name='expenserequisition',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expenserequisition',
            name='head_of_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.headofaccount'),
        ),
        migrations.AddField(
            model_name='expenserequisition',
            name='mr_or_bill_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='expenserequisition',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
