# Generated by Django 5.1.7 on 2026-02-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0056_alter_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequisition',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
