# Generated by Django 5.1.7 on 2026-02-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0057_expenserequisition_approval_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
