# Generated by Django 5.1.7 on 2026-02-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0058_requisition_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
