# Generated by Django 5.1.7 on 2026-07-27 06:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0092_balanceitem_project_name'),
        ('projects', '0031_remove_donation_donation_type'),
        ('purchase', '0059_alter_requisition_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillRequisitionApprovalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requi_uniq_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='BillRequisition Unique ID')),
                ('payment_type', models.CharField(default='requisition_pay', max_length=50)),
                ('requi_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('requisition_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.sitesupervisor')),
                ('debit_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.debitvoucher')),
                ('requi_item_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.headofrequisition')),
                ('requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_bill_payments', to='purchase.billrequisition')),
            ],
        ),
    ]
