# Generated by Django 5.1.7 on 2026-07-27 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0062_billrequisitionapprovalpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillRequisitionApprovalPayment',
        ),
    ]
