# Generated by Django 5.1.7 on 2026-08-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0064_billrequisitionapprovalpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='billrequisitionapprovalpayment',
            name='requi_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
