# Generated by Django 5.1.7 on 2025-05-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('nid', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('active_status', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
            ],
        ),
    ]
