# Generated by Django 5.1.7 on 2025-05-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_type',
            field=models.CharField(default='Employee', max_length=20),
        ),
    ]
