# Generated by Django 5.1.7 on 2025-05-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_alter_employee_emp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('accounts', 'Accounts'), ('hr', 'HR'), ('admin', 'Admin')], default='Employee', max_length=20),
        ),
    ]
