# Generated by Django 5.1.7 on 2025-05-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_alter_employee_emp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
