# Generated by Django 5.1.7 on 2025-05-15 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0005_employee_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user_name',
            new_name='userName',
        ),
    ]
