# Generated by Django 5.1.7 on 2025-05-15 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0006_rename_user_name_employee_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='userName',
            new_name='emp_name',
        ),
    ]
