# Generated by Django 5.1.7 on 2025-05-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0007_rename_username_employee_emp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('accounts', 'Accounts'), ('purchase', 'Purchase'), ('hr', 'HR'), ('admin', 'Admin')], default='Employee', max_length=20),
        ),
    ]
