# Generated by Django 5.1.7 on 2025-05-31 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0009_employee_user_alter_employee_emp_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_name',
        ),
    ]
