# Generated by Django 5.1.7 on 2025-05-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0010_remove_employee_emp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
