# Generated by Django 5.1.7 on 2025-06-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0014_alter_attendance_check_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(),
        ),
    ]
