# Generated by Django 5.1.7 on 2025-06-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0016_alter_attendance_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepayment',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
