# Generated by Django 5.1.7 on 2025-06-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0017_advancepayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('due', 'Due')], default='due', max_length=10),
        ),
    ]
