# Generated by Django 5.1.7 on 2025-06-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0018_alter_advancepayment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
