# Generated by Django 5.1.7 on 2025-06-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0019_employee_allowances'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowances_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
