# Generated by Django 5.1.7 on 2025-06-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0020_employee_allowances_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('accounts', 'Accounts'), ('purchase', 'Purchase'), ('hrm', 'HRM'), ('admin', 'Admin')], default='employee', max_length=20),
        ),
    ]
