# Generated by Django 4.2.20 on 2025-06-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0021_alter_employee_emp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('accounts', 'Accounts'), ('purchase', 'Purchase'), ('hrm', 'HRM'), ('admin', 'Admin'), ('engineer', 'Engineer')], default='employee', max_length=20),
        ),
    ]
