# Generated by Django 4.2.20 on 2025-06-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0023_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
