# Generated by Django 4.2.20 on 2025-06-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0024_alter_employee_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='allowances',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='allowances_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
