# Generated by Django 4.2.20 on 2025-06-27 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_capitalaccount'),
        ('hrm', '0025_remove_employee_allowances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepayment',
            name='cash_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.cashtype'),
        ),
        migrations.CreateModel(
            name='Allowances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('due', 'Due')], default='due', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.employee')),
            ],
        ),
    ]
