# Generated by Django 4.2.20 on 2025-06-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0026_advancepayment_cash_type_allowances'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepayment',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
