# Generated by Django 4.2.20 on 2025-07-07 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0045_alter_ledgerentry_type'),
        ('hrm', '0027_advancepayment_cheque_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowances',
            name='cash_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.cashtype'),
        ),
        migrations.AddField(
            model_name='allowances',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
