# Generated by Django 4.2.20 on 2025-07-10 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0049_alter_debitvoucher_approval_dr_status_and_more'),
        ('projects', '0023_contractoractivity'),
        ('hrm', '0028_allowances_cash_type_allowances_cheque_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepayment',
            name='head_of_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.headofaccount'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfirstlevelname'),
        ),
        migrations.AlterField(
            model_name='advancepayment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.employee'),
        ),
    ]
