# Generated by Django 4.2.20 on 2025-07-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0030_salarypayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarypayment',
            name='status',
        ),
    ]
