# Generated by Django 4.2.20 on 2025-07-25 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0057_ledgerentry_invest_name_alter_ledgerentry_capi_name'),
        ('projects', '0024_materialentry'),
        ('hrm', '0031_remove_salarypayment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowances',
            name='head_of_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.headofaccount'),
        ),
        migrations.AddField(
            model_name='allowances',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfirstlevelname'),
        ),
    ]
