# Generated by Django 4.2.20 on 2025-08-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0032_allowances_head_of_account_allowances_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='monthofsalary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
