# Generated by Django 4.2.20 on 2025-08-16 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_materialentry'),
        ('hrm', '0033_salarypayment_monthofsalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfirstlevelname'),
        ),
    ]
