# Generated by Django 4.2.20 on 2025-08-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0034_employee_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='att_status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], default='Present', max_length=20),
        ),
    ]
