# Generated by Django 4.2.20 on 2025-08-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0038_userbreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdaemployee',
            name='nid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
