# Generated by Django 4.2.20 on 2025-08-19 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0039_rdaemployee_nid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdaemployee',
            old_name='nid',
            new_name='rda_nid',
        ),
    ]
