# Generated by Django 4.2.20 on 2025-08-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0040_rename_nid_rdaemployee_rda_nid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdaemployee',
            name='rda_dofb',
            field=models.CharField(default='', max_length=100),
        ),
    ]
