# Generated by Django 4.2.20 on 2025-09-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0041_rdaemployee_rda_dofb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('accounts', 'Accounts'), ('purchase', 'Purchase'), ('hrm', 'HRM'), ('admin', 'Admin'), ('engineer', 'Engineer'), ('restaurant', 'Restaurant')], default='employee', max_length=20),
        ),
    ]
