# Generated by Django 4.2.20 on 2025-09-14 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0068_ledgerentry_tbl_id_ledgerentry_tbl_name'),
        ('projects', '0024_materialentry'),
        ('hrm', '0042_alter_employee_emp_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_month', models.DateField()),
                ('end_month', models.DateField()),
                ('month_name', models.CharField(blank=True, max_length=500, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('due', 'Due')], default='due', max_length=10)),
                ('cash_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.cashtype')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.employee')),
                ('head_of_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.headofaccount')),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfirstlevelname')),
            ],
        ),
    ]
