# Generated by Django 4.2.20 on 2025-09-15 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0043_loanpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.rdaemployee'),
        ),
    ]
