# Generated by Django 4.2.20 on 2025-09-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0044_alter_loanpayment_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpayment',
            name='deduction_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
