# Generated by Django 4.2.20 on 2025-09-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0046_alter_allowances_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowances',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('due', 'Due'), ('approved', 'Approved')], default='due', max_length=10),
        ),
    ]
