# Generated by Django 4.2.20 on 2025-09-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0047_alter_allowances_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='att_status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave'), ('Off Day', 'Off Day')], default='Present', max_length=20),
        ),
    ]
