# Generated by Django 4.2.20 on 2025-09-20 15:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_materialentry'),
        ('hrm', '0048_alter_attendance_att_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=20)),
                ('generate_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approval_salary_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=10)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfirstlevelname')),
            ],
        ),
    ]
