# Generated by Django 5.1.7 on 2025-12-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0051_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iom',
            name='end_date',
        ),
        migrations.AddField(
            model_name='iom',
            name='check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iom',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
