# Generated by Django 5.1.7 on 2025-12-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0052_remove_iom_end_date_iom_check_in_iom_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('accounts', 'Accounts'), ('purchase', 'Purchase'), ('hrm', 'HRM'), ('admin', 'Admin'), ('engineer', 'Engineer'), ('restaurant', 'Restaurant'), ('tenant', 'Tenant')], default='employee', max_length=20),
        ),
    ]
