# Generated by Django 5.1.7 on 2026-02-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0053_alter_employee_emp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='iom',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
