# Generated by Django 5.1.7 on 2026-05-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0054_iom_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdaemployee',
            name='rda_absent_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rdaemployee',
            name='rda_pay_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
