# Generated by Django 5.1.7 on 2026-05-19 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0055_rdaemployee_rda_absent_days_and_more'),
        ('projects', '0031_remove_donation_donation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdaemployee',
            name='rda_absent_days',
        ),
        migrations.RemoveField(
            model_name='rdaemployee',
            name='rda_pay_salary',
        ),
        migrations.CreateModel(
            name='RdaPayEmpSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rda_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rda_pay_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rda_absent_days', models.IntegerField(default=0)),
                ('pay_date', models.DateField()),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfirstlevelname')),
                ('rda_emp_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.rdaemployee')),
            ],
        ),
    ]
