# Generated by Django 5.1.7 on 2026-05-20 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0056_remove_rdaemployee_rda_absent_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowances',
            name='cash_type',
        ),
        migrations.RemoveField(
            model_name='allowances',
            name='cheque_number',
        ),
        migrations.RemoveField(
            model_name='allowances',
            name='head_of_account',
        ),
    ]
