# Generated by Django 5.1.7 on 2026-06-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0058_alter_employee_emp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('accounts', 'Accounts'), ('purchase', 'Purchase'), ('hrm', 'HRM'), ('admin', 'Admin'), ('engineer', 'Engineer'), ('restaurant', 'Restaurant'), ('tenant', 'Tenant'), ('designer', 'Designer'), ('btp', 'BTP')], default='employee', max_length=20),
        ),
    ]
