# Generated by Django 5.1.7 on 2026-07-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0063_attendanceaccesscontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceaccesscontrol',
            name='project_name',
            field=models.CharField(choices=[('BTP Office', 'BTP Office'), ('The Galleria Restaurant Cafe', 'The Galleria Restaurant Cafe'), ('The Galleria Live Kitchen', 'The Galleria Live Kitchen')], default='BTP Office', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendanceaccesscontrol',
            name='name',
            field=models.CharField(default='Attendance Access', max_length=100),
        ),
    ]
