# Generated by Django 5.1.7 on 2026-07-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0064_attendanceaccesscontrol_project_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceaccesscontrol',
            name='project_name',
        ),
        migrations.AlterField(
            model_name='attendanceaccesscontrol',
            name='name',
            field=models.CharField(default='BTP Office Attendance Access', max_length=100),
        ),
    ]
