# Generated by Django 5.1.7 on 2026-09-16 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0066_leave_handover_person_leave_leave_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdaemployee',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rda_employee', to='hrm.employee'),
        ),
    ]
