# Generated by Django 5.1.6 on 2025-02-09 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
