# Generated by Django 5.1.6 on 2025-02-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_delete_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'permissions': [('can_view_property', 'Can view property'), ('can_edit_property', 'Can edit property'), ('can_delete_property', 'Can delete property')]},
        ),
    ]
