# Generated by Django 5.1.6 on 2025-02-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('contact_information', models.TextField()),
                ('owner_type', models.CharField(max_length=50)),
                ('ownership_type', models.CharField(max_length=50)),
            ],
        ),
    ]
