# Generated by Django 5.1.6 on 2025-02-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propertyowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('project_start_date', models.DateField()),
                ('project_end_date', models.DateField()),
                ('project_status', models.CharField(max_length=50)),
            ],
        ),
    ]
