# Generated by Django 5.1.6 on 2025-02-19 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='description',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='price',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='property',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title',
        ),
        migrations.AddField(
            model_name='property',
            name='construction_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lease_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lease_status',
            field=models.CharField(default='Available', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.project'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='purchase_date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_status',
            field=models.CharField(default='Not Sold', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.propertyowner'),
        ),
    ]
