# Generated by Django 5.1.6 on 2025-02-19 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_rename_description_property_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JointVenture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=255)),
                ('partner_ownership_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('profit_share', models.DecimalField(decimal_places=2, max_digits=5)),
                ('revenue_share', models.DecimalField(decimal_places=2, max_digits=5)),
                ('jv_status', models.CharField(max_length=50)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
    ]
