# Generated by Django 5.1.6 on 2025-02-19 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_jointventure'),
    ]

    operations = [
        migrations.CreateModel(
            name='JVPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=255)),
                ('contact_information', models.TextField()),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('joint_venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='properties.jointventure')),
            ],
        ),
    ]
