# Generated by Django 5.1.6 on 2025-02-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_buyer_tenant_leaseagreement_leasepayment_salerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointventure',
            name='jv_status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated')], max_length=50),
        ),
    ]
