# Generated by Django 5.1.6 on 2025-02-21 06:35

import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_jointventure_jv_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jvpartner',
            name='contribution_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[properties.models.validate_contribution_amount]),
        ),
    ]
