# Generated by Django 5.1.6 on 2025-02-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_jvpartner_contribution_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='construction_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='project',
            name='flat_type_a',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='flat_type_b',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='flat_type_c',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='flat_type_d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='project',
            name='land_current_market_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='project',
            name='land_details_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='land_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='project',
            name='material_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='project',
            name='number_of_stories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='other_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='project',
            name='parking_details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='project',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
