# Generated by Django 5.1.6 on 2025-02-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_project_construction_cost_project_flat_type_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
