# Generated by Django 5.1.6 on 2025-03-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_alter_project_construction_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='profit_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='unit_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='construction_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='flat_type_a',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='flat_type_b',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='flat_type_c',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='flat_type_d',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='labor_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='land_current_market_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='land_details_area',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='land_purchase_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='material_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='number_of_stories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='other_costs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='parking_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='profit_margin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Unactive', 'Unactive')], max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='sales_price',
            field=models.IntegerField(),
        ),
    ]
