# Generated by Django 5.1.6 on 2025-03-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_alter_project_construction_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='construction_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='labor_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='land_current_market_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='land_details_area',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='land_purchase_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='material_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='other_costs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='profit_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='profit_margin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='sales_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='unit_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
