# Generated by Django 5.1.6 on 2025-03-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_alter_project_construction_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaseagreement',
            options={'verbose_name': 'Lease Agreement', 'verbose_name_plural': 'Lease Agreements'},
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='agreement_document',
            field=models.FileField(upload_to='lease_documents/'),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='lease_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='lease_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending'), ('Completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='payment_terms',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
