# Generated by Django 5.1.6 on 2025-03-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_alter_leaseagreement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='money_receipt_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='money_receipt_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='sale_agreement_document',
            field=models.FileField(upload_to='sale_agreements/'),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='sale_status',
            field=models.CharField(max_length=100),
        ),
    ]
