# Generated by Django 5.1.6 on 2025-03-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_salerecord_money_receipt_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='total_sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
