# Generated by Django 5.1.6 on 2025-03-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_buyer_total_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='total_lease_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
