# Generated by Django 5.1.7 on 2025-03-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_tenant_total_lease_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyowner',
            name='current_address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AddField(
            model_name='propertyowner',
            name='nid_card_details',
            field=models.FileField(default='nid_cards/default_nid_card.pdf', upload_to='nid_cards/'),
        ),
        migrations.AddField(
            model_name='propertyowner',
            name='photo',
            field=models.ImageField(blank=True, upload_to='owner_photos/'),
        ),
        migrations.AddField(
            model_name='propertyowner',
            name='telephone_number',
            field=models.CharField(default='Not Provided', max_length=20),
        ),
        migrations.AddField(
            model_name='propertyowner',
            name='utility_bill',
            field=models.FileField(blank=True, upload_to='utility_bills/'),
        ),
    ]
