# Generated by Django 5.1.7 on 2025-03-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_propertyowner_current_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='nid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='buyer_photos/'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='buyer_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Company', 'Company')], max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyowner',
            name='nid_card_details',
            field=models.FileField(upload_to='nid_cards/'),
        ),
    ]
