# Generated by Django 5.1.7 on 2025-05-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_buyer_nid_buyer_photo_alter_buyer_buyer_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_supplier', models.CharField(max_length=255)),
                ('mouza_name', models.CharField(blank=True, max_length=255)),
                ('cs_dag_no', models.CharField(blank=True, max_length=100)),
                ('sa_dag_no', models.CharField(blank=True, max_length=100)),
                ('rs_dag_no', models.CharField(blank=True, max_length=100)),
                ('ct_dag_no', models.CharField(blank=True, max_length=100)),
                ('did_agreement', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('agreement_date', models.DateField(blank=True, null=True)),
                ('land_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('land_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Agricultural', 'Agricultural')], max_length=50)),
                ('price_per_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank Transfer', 'Bank Transfer')], max_length=50)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Completed', 'Completed')], max_length=50)),
                ('deed_number', models.CharField(blank=True, max_length=100)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('registration_office', models.CharField(blank=True, max_length=255)),
                ('mutation_done', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('legal_dispute', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='land_documents/')),
            ],
        ),
    ]
