# Generated by Django 5.1.7 on 2025-05-25 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_landpurchase_created_at_landpurchase_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jointventure',
            name='property',
        ),
        migrations.AddField(
            model_name='jointventure',
            name='land_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.landpurchase'),
        ),
    ]
