# Generated by Django 5.1.7 on 2025-05-25 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0027_remove_jointventure_property_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaseagreement',
            name='property',
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='land_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.landpurchase'),
        ),
    ]
