# Generated by Django 5.1.7 on 2025-06-20 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_remove_leaseagreement_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landpurchase',
            name='land_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertyowner'),
        ),
    ]
