# Generated by Django 4.2.20 on 2025-07-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0029_alter_landpurchase_land_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landpurchase',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='landpurchase',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='landpurchase',
            name='registration_office',
        ),
    ]
