# Generated by Django 4.2.20 on 2025-09-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_remove_landpurchase_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointventure',
            name='developer_flat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jointventure',
            name='developer_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jointventure',
            name='land_owner_flat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jointventure',
            name='land_owner_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jointventure',
            name='photo',
            field=models.ImageField(blank=True, upload_to='plan_photos/'),
        ),
        migrations.AddField(
            model_name='jointventure',
            name='signing_money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
