# Generated by Django 4.2.20 on 2025-09-21 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0031_jointventure_developer_flat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jointventure',
            old_name='partner_name',
            new_name='developer_name',
        ),
        migrations.AddField(
            model_name='jointventure',
            name='land_owner_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.propertyowner'),
        ),
    ]
