# Generated by Django 4.2.20 on 2025-09-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0032_rename_partner_name_jointventure_developer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointventure',
            name='profit_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='jointventure',
            name='revenue_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
