# Generated by Django 4.2.20 on 2025-09-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0033_alter_jointventure_profit_share_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jointventure',
            name='partner_ownership_percentage',
        ),
        migrations.AddField(
            model_name='jointventure',
            name='developer_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='jointventure',
            name='land_owner_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
