# Generated by Django 4.2.20 on 2025-09-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0034_remove_jointventure_partner_ownership_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landpurchase',
            name='lilahetalah_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='landpurchase',
            name='lilahetalah_per',
            field=models.CharField(default='', max_length=20),
        ),
    ]
