# Generated by Django 4.2.20 on 2025-10-18 09:33

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0035_landpurchase_lilahetalah_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=100)),
                ('type_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('type_note', models.CharField(default='', max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandHeadOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_name', models.CharField(max_length=255)),
                ('head_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='landpurchase',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='landpurchase',
            name='gross_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='landpurchase',
            name='media_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='landpurchase',
            name='media_per',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='LandTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.CharField(blank=True, max_length=255, null=True)),
                ('particulars', models.TextField(blank=True, null=True)),
                ('cash_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.cashmethod')),
                ('head_of_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.landheadofaccount')),
                ('land_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.landpurchase')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertyowner')),
            ],
        ),
        migrations.CreateModel(
            name='LandLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mr_or_bill_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('carrier', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_status', models.CharField(blank=True, max_length=255, null=True)),
                ('tbl_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tbl_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cash_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.cashmethod')),
                ('head_of_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.landheadofaccount')),
                ('land_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.landpurchase')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertyowner')),
            ],
        ),
        migrations.CreateModel(
            name='LandDebitVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mr_or_bill_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date', models.DateField()),
                ('remark', models.TextField()),
                ('approval_status', models.BooleanField(blank=True, null=True)),
                ('carrier', models.CharField(blank=True, max_length=255, null=True)),
                ('create_dr_by', models.CharField(blank=True, max_length=255, null=True)),
                ('cash_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.cashmethod')),
                ('head_of_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.landheadofaccount')),
                ('land_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.landpurchase')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertyowner')),
            ],
        ),
        migrations.CreateModel(
            name='LandCreditVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('mr_or_bill_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remark', models.TextField()),
                ('approval_status', models.BooleanField(default=False)),
                ('carrier', models.CharField(blank=True, max_length=255, null=True)),
                ('create_cr_by', models.CharField(blank=True, max_length=255, null=True)),
                ('cash_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.cashmethod')),
                ('head_of_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.landheadofaccount')),
                ('land_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.landpurchase')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertyowner')),
            ],
        ),
        migrations.CreateModel(
            name='LandApprovalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_uniq_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Land Unique ID')),
                ('payment_type', models.CharField(default='purchase_pay', max_length=50)),
                ('purch_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('debit_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.landdebitvoucher')),
                ('land_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.landpurchase')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertyowner')),
            ],
        ),
    ]
