# Generated by Django 4.2.20 on 2025-10-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0036_cashmethod_landheadofaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landpurchase',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='land_signatures/'),
        ),
    ]
