# Generated by Django 4.2.20 on 2025-10-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0037_landpurchase_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='landcreditvoucher',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landdebitvoucher',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landledgerentry',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landtransactionhistory',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
