# Generated by Django 4.2.20 on 2025-10-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0038_landcreditvoucher_type_landdebitvoucher_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandHeadOfExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_exp_name', models.CharField(max_length=255)),
                ('head_exp_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
    ]
