# Generated by Django 4.2.20 on 2025-10-19 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0039_landheadofexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='landcreditvoucher',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.landheadofexpense'),
        ),
        migrations.AddField(
            model_name='landdebitvoucher',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.landheadofexpense'),
        ),
        migrations.AddField(
            model_name='landledgerentry',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.landheadofexpense'),
        ),
        migrations.AddField(
            model_name='landtransactionhistory',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.landheadofexpense'),
        ),
    ]
