# Generated by Django 4.2.20 on 2025-10-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0040_landcreditvoucher_expense_landdebitvoucher_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landtransactionhistory',
            name='tbl_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
