# Generated by Django 4.2.20 on 2025-10-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0041_landtransactionhistory_tbl_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='landdebitvoucher',
            name='advance_pay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
