# Generated by Django 4.2.20 on 2025-10-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0042_landdebitvoucher_advance_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='landledgerentry',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landtransactionhistory',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
