# Generated by Django 5.1.7 on 2026-06-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0043_landledgerentry_cheque_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landpurchase',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
