# Generated by Django 5.1.7 on 2026-06-24 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0044_landpurchase_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('file_no', models.CharField(max_length=100, unique=True)),
                ('work_type', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('responsible', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('owner_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='properties.propertyowner')),
            ],
        ),
    ]
