# Generated by Django 5.1.7 on 2026-06-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0045_recordfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfile',
            name='owner_client',
            field=models.CharField(max_length=255),
        ),
    ]
