# Generated by Django 5.1.7 on 2026-06-26 12:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0047_recordfile_file_type_alter_recordfile_file_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_no', models.CharField(max_length=100, unique=True, verbose_name='File No')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('area', models.CharField(max_length=200, verbose_name='Area / Location')),
                ('land_dag_no', models.CharField(max_length=100, verbose_name='Land Dag No')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Land Record',
                'verbose_name_plural': 'Land Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Owner Name')),
                ('note', models.TextField(blank=True, verbose_name='Note / Description')),
                ('step_label', models.CharField(blank=True, help_text="E.g. 'Original Owner', 'First Heir', 'Second Generation'", max_length=200, verbose_name='Step Label')),
                ('relation', models.CharField(blank=True, help_text="E.g. 'Son', 'Daughter', 'Wife', 'Brother'", max_length=200, verbose_name='Relation')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='properties.landowner')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='properties.landrecord')),
            ],
            options={
                'verbose_name': 'Land Owner',
                'verbose_name_plural': 'Land Owners',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
