# Generated by Django 5.1.7 on 2026-06-26 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0048_landrecord_landowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landowner',
            name='land',
        ),
        migrations.RemoveField(
            model_name='landowner',
            name='parent',
        ),
        migrations.DeleteModel(
            name='LandRecord',
        ),
        migrations.DeleteModel(
            name='LandOwner',
        ),
    ]
