# Generated by Django 5.1.7 on 2026-06-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0049_remove_landowner_land_remove_landowner_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordfile',
            name='dag_no',
            field=models.CharField(default='', max_length=255),
        ),
    ]
