# Generated by Django 5.1.7 on 2026-06-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0050_recordfile_dag_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfile',
            name='dag_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recordfile',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recordfile',
            name='file_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='recordfile',
            name='owner_client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recordfile',
            name='responsible',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recordfile',
            name='work_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
