# Generated by Django 5.1.7 on 2026-06-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0051_alter_recordfile_dag_no_alter_recordfile_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfile',
            name='status',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
