# Generated by Django 5.1.7 on 2026-06-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0052_alter_recordfile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfile',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
