# Generated by Django 5.1.7 on 2026-06-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0053_alter_recordfile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfile',
            name='responsible',
            field=models.TextField(blank=True, null=True),
        ),
    ]
