# Generated by Django 5.1.7 on 2026-06-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0054_alter_recordfile_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfile',
            name='file_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
