# Generated by Django 5.1.7 on 2026-06-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0055_alter_recordfile_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandDocument',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False, verbose_name='ক্রমিক')),
                ('file_code', models.CharField(choices=[('DL', 'DL (মূল দলিল)'), ('BY', 'BY (বায়না)'), ('HB', 'HB (হেবা)'), ('POA', 'POA (আমমোক্তারনামা)'), ('MT', 'MT (নামজারি)'), ('RS', 'RS (রেকর্ড)'), ('MAP', 'MAP (নকশা)'), ('TAX', 'TAX (খাজনা)')], max_length=10, verbose_name='ফাইল কোড')),
                ('doc_no', models.CharField(max_length=100, verbose_name='দলিল নং')),
                ('doc_type', models.CharField(max_length=100, verbose_name='দলিলের ধরন')),
                ('doc_date', models.DateField(verbose_name='দলিলের তারিখ')),
                ('seller', models.CharField(max_length=255, verbose_name='বিক্রেতা')),
                ('buyer', models.CharField(max_length=255, verbose_name='ক্রেতা')),
                ('mouza', models.CharField(max_length=255, verbose_name='মৌজা')),
                ('khatian', models.CharField(max_length=100, verbose_name='খতিয়ান')),
                ('dag_no', models.CharField(max_length=100, verbose_name='দাগ নং')),
                ('land_amount', models.CharField(max_length=100, verbose_name='জমির পরিমাণ')),
                ('project_block', models.CharField(max_length=255, verbose_name='প্রকল্প/ব্লক')),
                ('file_location', models.CharField(max_length=255, verbose_name='ফাইল লোকেশন')),
                ('scanned_copy', models.FileField(blank=True, null=True, upload_to='scanned_docs/', verbose_name='স্ক্যান কপি')),
                ('current_status', models.CharField(max_length=100, verbose_name='বর্তমান অবস্থা')),
                ('assigned_person', models.CharField(max_length=255, verbose_name='দায়িত্বপ্রাপ্ত')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='সর্বশেষ আপডেট')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='মন্তব্য')),
            ],
        ),
    ]
