# Generated by Django 5.1.7 on 2026-07-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0056_landdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordfile',
            name='area',
            field=models.CharField(blank=True, choices=[('Acore', 'Acore'), ('Decimel', 'Decimel'), ('Kata', 'Kata')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recordfile',
            name='file_type',
            field=models.CharField(blank=True, choices=[('RF', 'Real Estate File'), ('LF', 'Land File'), ('LGF', 'Legal File'), ('CF', 'Contractor File'), ('CCF', 'Civil Contractor File'), ('ECF', 'Electrical Contractor File'), ('PCF', 'Plumbing Contractor File'), ('MCF', 'Mechanical Contractor File'), ('FCF', 'Finishing Contractor File'), ('SCF', 'Supplier & Contractor File')], max_length=50, null=True),
        ),
    ]
