# Generated by Django 5.1.7 on 2026-07-01 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0057_recordfile_area_alter_recordfile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landdocument',
            name='file_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.recordfile', verbose_name='ফাইল লোকেশন'),
        ),
    ]
