# Generated by Django 5.1.7 on 2026-07-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0058_alter_landdocument_file_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordfile',
            old_name='dag_no',
            new_name='area_value',
        ),
        migrations.AddField(
            model_name='recordfile',
            name='cs_dag_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recordfile',
            name='ct_dag_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recordfile',
            name='mouza',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recordfile',
            name='rs_dag_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recordfile',
            name='sa_dag_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
