# Generated by Django 5.1.7 on 2026-09-12 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Label shown in the sidebar, e.g. 'Employee Document'", max_length=100)),
                ('icon', models.CharField(blank=True, default='circle', help_text="Lucide icon name used elsewhere in the UI, e.g. 'activity', 'home'", max_length=50)),
                ('url_name', models.CharField(blank=True, help_text="Django URL name used in {% url %}, e.g. 'employee_list'. Leave blank if this row is only a dropdown parent (has children).", max_length=100)),
                ('permission', models.CharField(blank=True, help_text="Optional fallback, only used if no Groups or Users are selected below. Exact Django permission codename, e.g. 'accounting.view_creditvoucher' (app_label.codename — same format shown in the 'Chosen user permissions' box in /admin/).", max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide this item for everyone without deleting it.')),
                ('groups', models.ManyToManyField(blank=True, help_text='Which group(s) can see this item — pick one or several. Superusers always see every item regardless of this field.', related_name='menu_items', to='auth.group')),
                ('parent', models.ForeignKey(blank=True, help_text="Leave blank for a top-level section (e.g. 'HRM'). Set to a parent row for a link that lives inside a dropdown.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu_app.menuitem')),
                ('users', models.ManyToManyField(blank=True, help_text='Which specific user(s) can see this item — pick one or several. Superusers always see every item regardless of this field.', related_name='menu_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
