# Generated by Django 5.1.7 on 2026-09-12 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMenuOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restrict_superuser', models.BooleanField(default=False, help_text="Tick to make this superuser's sidebar follow normal group/user rules instead of showing everything.")),
                ('user', models.OneToOneField(limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, related_name='menu_override', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
