# Generated by Django 5.1.6 on 2025-02-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_propertyassociation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('can_view_document', 'Can view document'), ('can_upload_document', 'Can upload document'), ('can_delete_document', 'Can delete document'), ('can_edit_document', 'Can edit document')]},
        ),
        migrations.AlterModelOptions(
            name='documentversion',
            options={'permissions': [('can_view_version', 'Can view document version'), ('can_delete_version', 'Can delete document version'), ('can_download_version', 'Can download document version')]},
        ),
    ]
