# Generated by Django 5.1.6 on 2025-02-10 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_options_alter_documentversion_options'),
        ('properties', '0004_alter_property_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyassociation',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
    ]
