# Generated by Django 5.1.6 on 2025-02-10 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_propertyassociation_property'),
        ('properties', '0004_alter_property_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyassociation',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
    ]
