# Generated by Django 5.1.6 on 2025-02-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_propertyassociation_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='property_association',
        ),
        migrations.AddField(
            model_name='document',
            name='property_association',
            field=models.ManyToManyField(related_name='documents', to='documents.propertyassociation'),
        ),
    ]
