# Generated by Django 5.1.6 on 2025-02-27 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_document_property_association_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='property_association',
        ),
        migrations.AddField(
            model_name='document',
            name='property_association',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documents.propertyassociation'),
        ),
    ]
