# Generated by Django 5.1.6 on 2025-02-27 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_remove_document_property_association_and_more'),
        ('properties', '0014_alter_project_profit_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='property_association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property'),
        ),
    ]
