# Generated by Django 5.1.6 on 2025-02-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_rename_uploaded_at_file_created_at_alter_file_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
