# Generated by Django 5.1.6 on 2025-03-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='folder',
        ),
    ]
