# Generated by Django 5.1.7 on 2025-06-15 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_remove_uploadedfile_folder'),
        ('properties', '0028_remove_leaseagreement_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='property_association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.landpurchase'),
        ),
    ]
