# Generated by Django 5.1.7 on 2026-05-26 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_empuploadedfile_empfile_empfolder'),
        ('hrm', '0057_remove_allowances_cash_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empfile',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.employee'),
        ),
        migrations.AddField(
            model_name='empfolder',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.employee'),
        ),
        migrations.AddField(
            model_name='empuploadedfile',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.employee'),
        ),
    ]
