# Generated by Django 5.1.7 on 2026-05-26 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_empfile_employee_empfolder_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empfile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.empfolder'),
        ),
    ]
