# Generated by Django 5.1.7 on 2026-05-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_alter_empfile_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empfile',
            name='file',
            field=models.FileField(upload_to='emp_files/'),
        ),
        migrations.AlterField(
            model_name='empuploadedfile',
            name='file',
            field=models.FileField(upload_to='emp_uploads/'),
        ),
    ]
