# Generated by Django 5.1.7 on 2026-06-28 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_trackeruploadedfile_trackerfolder_trackerfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerGoogleDriveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('google_drive_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_drive_link', models.URLField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='google_files', to='documents.trackerfolder')),
            ],
        ),
    ]
