# Generated by Django 5.1.7 on 2026-06-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_trackergoogledrivefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackergoogledrivefile',
            name='file',
        ),
        migrations.AlterField(
            model_name='trackergoogledrivefile',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
