# Generated by Django 5.1.7 on 2026-07-31 14:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=20, unique=True)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitemcategory',
            name='color_code',
            field=models.CharField(default='#1e293b', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('VISA', 'Visa'), ('AMEX', 'Amex'), ('MASTERCARD', 'Mastercard'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.menuitemcategory'),
        ),
        migrations.AlterField(
            model_name='restaurantorder',
            name='channel',
            field=models.CharField(choices=[('DINE_IN', 'Dine In'), ('FOODPANDA', 'Foodpanda'), ('FOODI', 'Foodi'), ('PATHAO', 'Pathao'), ('DELIVERY', 'Delivery'), ('TAKEAWAY', 'Takeaway')], default='DINE_IN', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.restauranttable'),
        ),
        migrations.CreateModel(
            name='WorkPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_periods', to=settings.AUTH_USER_MODEL)),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_periods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='work_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.workperiod'),
        ),
    ]
