from django.contrib import admin
from .models import *

admin.site.register(Varatiya)
admin.site.register(Room)
admin.site.register(ProjectName)
admin.site.register(Rent)
admin.site.register(Bill)
admin.site.register(GasBill)
admin.site.register(WaterBill)
admin.site.register(ParkingBill)
admin.site.register(ElectricityBill)
admin.site.register(ServiceBill)
admin.site.register(GarbageBill)
admin.site.register(MainBill)
admin.site.register(TenantCashType)
admin.site.register(ChequeBook)
admin.site.register(Cheque)
admin.site.register(TenantAdvance)
admin.site.register(ReceiveVoucher)
admin.site.register(PaymentVoucher)
admin.site.register(LedgerEntry)
admin.site.register(Attendance)
admin.site.register(TenantBulkSMS)
admin.site.register(TenantBulkSMSRecipient)
admin.site.register(Supplier)