# Generated by Django 5.1.7 on 2026-06-17 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0058_alter_employee_emp_type'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetask',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='employeetask',
            name='object_id',
        ),
        migrations.AddField(
            model_name='employeetask',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='hrm.rdaemployee'),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
