# Generated by Django 5.1.7 on 2026-06-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_employeetask_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetask',
            name='emp_attachment',
            field=models.FileField(blank=True, null=True, upload_to='task_emp_attachments/'),
        ),
    ]
