# Generated by Django 5.1.7 on 2025-05-20 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0017_projectfirstlevelname_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customers/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=255)),
                ('first_contact_date', models.DateField(blank=True, null=True)),
                ('first_contact_note', models.TextField(blank=True)),
                ('second_contact_date', models.DateField(blank=True, null=True)),
                ('second_contact_note', models.TextField(blank=True)),
                ('third_contact_date', models.DateField(blank=True, null=True)),
                ('third_contact_note', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='crm.customer')),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfirstlevelname')),
            ],
        ),
    ]
