# Generated by Django 4.2.20 on 2025-07-02 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer_assign_to_user_customer_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFollowup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=255)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('followup_note', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customerlead',
            old_name='second_contact_date',
            new_name='followup_date',
        ),
        migrations.RenameField(
            model_name='customerlead',
            old_name='second_contact_note',
            new_name='followup_note',
        ),
        migrations.RemoveField(
            model_name='customerlead',
            name='third_contact_date',
        ),
        migrations.RemoveField(
            model_name='customerlead',
            name='third_contact_note',
        ),
        migrations.AlterField(
            model_name='customerlead',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_leads', to='crm.customer'),
        ),
    ]
