# Generated by Django 4.2.20 on 2025-07-15 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_contractoractivity'),
        ('crm', '0003_customerfollowup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_agent', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='', max_length=20)),
                ('sale_date', models.DateField()),
                ('booking_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('online', 'Online Payment'), ('other', 'Other')], max_length=50)),
                ('sale_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('payment_received', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance_due', models.DecimalField(decimal_places=2, max_digits=15)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.customer')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.projectfirstlevelname')),
            ],
        ),
    ]
