# Generated by Django 4.2.20 on 2025-07-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sales_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount applied on the sale', max_digits=15),
        ),
        migrations.AlterField(
            model_name='sale',
            name='balance_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
