# Generated by Django 4.2.20 on 2025-08-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_sale_sales_discount_alter_sale_balance_due'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustInfoBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('profession', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nid', models.CharField(max_length=15)),
                ('dateofbrith', models.DateField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customers/')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
