# Generated by Django 5.1.7 on 2026-01-19 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_bulksms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulksms',
            name='recipients',
        ),
        migrations.CreateModel(
            name='BulkSMSRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('bulk_sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='crm.bulksms')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
            ],
        ),
    ]
