# Generated by Django 5.1.7 on 2026-09-15 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_bulksms_recipients_bulksmsrecipient'),
        ('projects', '0033_alter_boreviseditem_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfollowup',
            name='communication_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerfollowup',
            name='salesperson_marking',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customerlead',
            name='customer_feedback_rating',
            field=models.IntegerField(default=0, help_text='Customer rating (1-5)'),
        ),
        migrations.AddField(
            model_name='customerlead',
            name='salesperson_marking_possibility',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Sales possibility percentage', max_digits=5),
        ),
        migrations.AlterField(
            model_name='customer',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads_customer', to='projects.projectfirstlevelname'),
        ),
        migrations.AlterField(
            model_name='customerlead',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close'), ('junk', 'Junk')], default='open', max_length=10),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='campaigns/')),
                ('remark', models.TextField(blank=True, null=True)),
                ('campaign_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='projects.projectfirstlevelname')),
            ],
        ),
        migrations.AddField(
            model_name='customerlead',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_campaigns', to='crm.campaign'),
        ),
    ]
