# Generated by Django 5.1.7 on 2026-09-15 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_customerfollowup_communication_status_and_more'),
        ('projects', '0033_alter_boreviseditem_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerfollowup',
            name='lead_id',
        ),
        migrations.AddField(
            model_name='customerfollowup',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='crm.customerlead'),
        ),
        migrations.AlterField(
            model_name='customerlead',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfirstlevelname'),
        ),
    ]
