# Generated by Django 5.1.7 on 2026-09-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_remove_customerfollowup_lead_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerfollowup',
            options={'ordering': ['-create_date']},
        ),
        migrations.AddField(
            model_name='customer',
            name='anniversary_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customerfollowup',
            name='activity_type',
            field=models.CharField(choices=[('followup', 'Followup'), ('task_visit', 'Task/Visit')], default='followup', max_length=20),
        ),
        migrations.AddField(
            model_name='customerfollowup',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerfollowup',
            name='next_activity_type',
            field=models.CharField(blank=True, choices=[('followup', 'Followup'), ('task_visit', 'Task/Visit')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerfollowup',
            name='next_followup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerfollowup',
            name='next_followup_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerfollowup',
            name='task_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerfollowup',
            name='task_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerfollowup',
            name='task_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerfollowup',
            name='visit_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerlead',
            name='cr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='If CR'),
        ),
        migrations.AddField(
            model_name='customerlead',
            name='lead_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerlead',
            name='lead_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='customerlead',
            name='stage',
            field=models.CharField(choices=[('New', 'New'), ('Booking', 'Booking'), ('Booked', 'Booked'), ('Negotiation Meeting', 'Negotiation Meeting'), ('Sold', 'Sold'), ('Junk', 'Junk')], default='New', max_length=30),
        ),
    ]
