# Generated by Django 5.1.7 on 2026-09-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_customerfollowup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlead',
            name='query',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
