# Generated by Django 5.1.7 on 2026-09-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_customerlead_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulksmsrecipient',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_agent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
