# Generated by Django 5.1.7 on 2026-09-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_bulksmsrecipient_status_alter_sale_sales_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfollowup',
            name='task_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
