# Generated by Django 4.2.20 on 2025-08-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurantsale_discount_restaurantsale_final_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsaleitem',
            name='discount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurantsaleitem',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
