# Generated by Django 4.2.20 on 2025-09-12 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurantsaleitem_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_supplier_name', models.CharField(max_length=255)),
                ('rest_supplier_account', models.CharField(default='Supplier Account', max_length=255)),
                ('rest_supplier_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestHeadofAcct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restu_headofacct_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_acct_name', models.CharField(max_length=255)),
                ('rest_acct_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('rest_head_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restheadofacct')),
            ],
        ),
    ]
