# Generated by Django 5.1.7 on 2026-03-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_restaurantsupplier_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=200)),
                ('expense_code', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
