# Generated by Django 5.1.7 on 2026-03-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_restexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restexpense',
            name='expense_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
