# Generated by Django 5.1.7 on 2026-03-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_restexpense_expense_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestPurchaseCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur_cost_name', models.CharField(max_length=200)),
                ('pur_cost_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
    ]
