# Generated by Django 5.1.7 on 2026-03-27 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_remove_donation_donation_type'),
        ('restaccounting', '0037_alter_ledgerrestentry_type'),
        ('restahrm', '0043_alter_restaurantfoodbillpayment_customer_type'),
        ('restaurant', '0008_restpurchasecost'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestExpenseRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('mr_or_bill_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('descript', models.CharField(max_length=100)),
                ('remark', models.TextField(blank=True, null=True)),
                ('approv_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('ledger_add', models.BooleanField(blank=True, null=True)),
                ('approv_note', models.TextField(blank=True, null=True)),
                ('requi_expense_id', models.IntegerField(blank=True, null=True)),
                ('requisition_date', models.DateField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('cash_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaccounting.cashresttype')),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restahrm.restaurantemployee')),
                ('head_of_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaccounting.restheadofaccount')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restexpense')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname')),
            ],
        ),
    ]
