# Generated by Django 5.1.7 on 2026-04-18 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0054_iom_end_date'),
        ('restaurant', '0009_restexpenserequisition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restexpenserequisition',
            name='employee_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.employee'),
        ),
    ]
