# Generated by Django 5.1.7 on 2026-06-06 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0057_remove_allowances_cash_type_and_more'),
        ('projects', '0031_remove_donation_donation_type'),
        ('restaurant', '0010_alter_restexpenserequisition_employee_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=50)),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(max_length=100)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('description', models.CharField(default='', max_length=500)),
                ('remark', models.TextField(blank=True, null=True)),
                ('approv_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approv_note', models.TextField(blank=True, null=True)),
                ('approv_acct_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approv_acct_note', models.TextField(blank=True, null=True)),
                ('approv_purch_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approv_purch_note', models.TextField(blank=True, null=True)),
                ('return_requisition', models.CharField(blank=True, max_length=100, null=True)),
                ('requisition_date', models.DateField(blank=True, null=True)),
                ('requi_uniq_id', models.IntegerField(blank=True, null=True)),
                ('purch_appov', models.CharField(blank=True, max_length=20, null=True)),
                ('purch_date', models.DateField(blank=True, null=True)),
                ('purch_id', models.IntegerField(blank=True, null=True)),
                ('return_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('return_status', models.CharField(blank=True, max_length=20, null=True)),
                ('cash_empl', models.CharField(blank=True, max_length=20, null=True)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.employee')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantitem')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname')),
            ],
        ),
    ]
