# Generated by Django 5.1.7 on 2026-06-07 05:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0057_remove_allowances_cash_type_and_more'),
        ('projects', '0031_remove_donation_donation_type'),
        ('restaurant', '0011_restrequisition'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestInventories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requi_id', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(max_length=100)),
                ('qty', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('approv_note', models.TextField(blank=True, null=True)),
                ('approv_acct_note', models.TextField(blank=True, null=True)),
                ('approv_purch_note', models.TextField(blank=True, null=True)),
                ('requisition_date', models.DateField(blank=True, null=True)),
                ('qtysub', models.PositiveIntegerField(default=0)),
                ('purch_id', models.IntegerField(blank=True, null=True)),
                ('purch_date', models.DateField(blank=True, null=True)),
                ('purch_file_1', models.ImageField(blank=True, null=True, upload_to='purchase_docs/')),
                ('purch_file_2', models.ImageField(blank=True, null=True, upload_to='purchase_docs/')),
                ('purch_file_3', models.ImageField(blank=True, null=True, upload_to='purchase_docs/')),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.employee')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantitem')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname')),
                ('vendor_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantsupplier')),
            ],
        ),
        migrations.CreateModel(
            name='RestInventoryUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('total_qty', models.PositiveIntegerField(default=0)),
                ('qtysub_qty', models.PositiveIntegerField(default=0)),
                ('details', models.TextField(blank=True, null=True)),
                ('use_date', models.DateField(default=django.utils.timezone.now)),
                ('remark', models.TextField(blank=True, null=True)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantitem')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname')),
            ],
        ),
    ]
