# Generated by Django 5.1.7 on 2026-06-14 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0044_remove_restaurantallowances_cash_type_and_more'),
        ('restaurant', '0013_alter_restrequisition_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restinventories',
            name='employee_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restahrm.restaurantemployee'),
        ),
    ]
