# Generated by Django 5.1.7 on 2026-06-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_alter_restinventories_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrequisition',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True),
        ),
    ]
