# Generated by Django 5.1.7 on 2026-06-16 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_alter_restrequisition_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrequisition',
            name='vendor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.restaurantsupplier'),
        ),
    ]
