# Generated by Django 5.1.7 on 2026-06-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_alter_restrequisition_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrequisition',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='restrequisition',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
