# Generated by Django 5.1.7 on 2026-06-17 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_remove_donation_donation_type'),
        ('restahrm', '0044_remove_restaurantallowances_cash_type_and_more'),
        ('restaurant', '0017_alter_restrequisition_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestRequisitionApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requi_uniq_id', models.IntegerField(blank=True, null=True)),
                ('purch_appov', models.CharField(blank=True, max_length=20, null=True)),
                ('cash_empl', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('approv_acct_status', models.CharField(max_length=20)),
                ('approv_acct_note', models.TextField(blank=True, null=True)),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requisitions', to='restahrm.restaurantemployee')),
                ('employee_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restahrm.restaurantemployee')),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfirstlevelname')),
            ],
        ),
    ]
