# Generated by Django 5.1.7 on 2026-06-17 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0057_remove_allowances_cash_type_and_more'),
        ('restaurant', '0018_restrequisitionapprovalhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrequisitionapprovalhistory',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requisitions', to='hrm.employee'),
        ),
    ]
