# Generated by Django 5.1.7 on 2026-06-20 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_remove_donation_donation_type'),
        ('restaurant', '0019_alter_restrequisitionapprovalhistory_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantPublicExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restu_expense_name', models.CharField(max_length=255)),
                ('restu_expense_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname')),
                ('restu_cate_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantcategory')),
            ],
        ),
    ]
