# Generated by Django 5.1.7 on 2026-06-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_restaurantpublicexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantpublicexpense',
            name='restu_expense_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
