# Generated by Django 5.1.7 on 2026-06-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0022_alter_restaurantpublicexpense_restu_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantpublicexpense',
            name='restu_expense_type',
            field=models.CharField(choices=[('', '-- Select Type --'), ('Expense', 'Expense'), ('Bazar', 'Bazar')], default='Expense', max_length=20),
        ),
    ]
