# Generated by Django 5.1.7 on 2026-06-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0023_alter_restaurantpublicexpense_restu_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrequisition',
            name='approv_purch_store',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
