# Generated by Django 5.1.7 on 2026-06-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_restrequisition_approv_purch_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restrequisition',
            old_name='approv_purch_store',
            new_name='approv_store',
        ),
    ]
