# Generated by Django 5.1.7 on 2026-07-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0025_rename_approv_purch_store_restrequisition_approv_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantJewelSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_supplier_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('rest_supplier_account', models.CharField(default='Supplier Account', max_length=255)),
                ('rest_supplier_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('purchase_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
