# Generated by Django 5.1.7 on 2026-07-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_restaurantjewelsupplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrequisition',
            name='calc_mode',
            field=models.CharField(choices=[('normal', 'Normal'), ('unit', 'Unit')], default='normal', max_length=10),
        ),
    ]
