# Generated by Django 5.1.7 on 2026-07-04 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restahrm', '0044_remove_restaurantallowances_cash_type_and_more'),
        ('restaurant', '0027_restrequisition_calc_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrequisitionapprovalhistory',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requisitions', to='restahrm.restaurantemployee'),
        ),
    ]
