# Generated by Django 5.1.7 on 2026-07-04 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0060_alter_employee_emp_type'),
        ('restaurant', '0028_alter_restrequisitionapprovalhistory_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrequisitionapprovalhistory',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requisitions', to='hrm.employee'),
        ),
    ]
