# Generated by Django 5.1.7 on 2026-07-09 14:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_remove_donation_donation_type'),
        ('restahrm', '0044_remove_restaurantallowances_cash_type_and_more'),
        ('restaurant', '0029_alter_restrequisitionapprovalhistory_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantKitchenLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='restahrm.restaurantemployee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='projects.projectfirstlevelname')),
                ('requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='restaurant.restrequisition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
