# Generated by Django 5.1.7 on 2026-07-10 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0031_restaurantkitchenledger_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantkitchenledger',
            name='item_name',
        ),
    ]
