# Generated by Django 5.1.7 on 2026-07-10 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0032_remove_restaurantkitchenledger_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantkitchenledger',
            name='item_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantitem'),
        ),
    ]
