# Generated by Django 5.1.7 on 2026-07-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0033_restaurantkitchenledger_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantkitchenledger',
            name='pay_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
