# Generated by Django 5.1.7 on 2026-07-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0034_restaurantkitchenledger_pay_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantkitchenledger',
            name='pay_type',
        ),
        migrations.AddField(
            model_name='restaurantkitchenledger',
            name='type',
            field=models.CharField(blank=True, choices=[('Expense', 'Expense'), ('Purchase', 'Purchase')], max_length=20, null=True),
        ),
    ]
