# Generated by Django 5.1.7 on 2026-07-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0036_approvalrange_restaurantbudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrequisitionapprovalhistory',
            name='pur_verify',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
