# Generated by Django 5.1.7 on 2026-07-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0037_restrequisitionapprovalhistory_pur_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restu_Exp_category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='restaurantpublicexpense',
            name='restu_expense_type',
            field=models.CharField(choices=[('Expense', 'Expense')], default='Expense', max_length=20),
        ),
    ]
