# Generated by Django 5.1.7 on 2026-07-21 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0040_alter_restaurantpublicexpense_restu_cate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantpublicexpense',
            name='restu_cate_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantexpensecategory'),
        ),
    ]
