# Generated by Django 5.1.7 on 2026-07-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0041_alter_restaurantpublicexpense_restu_cate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantkitchenledger',
            name='tbl_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
