# Generated by Django 5.1.7 on 2026-07-31 18:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0042_restaurantkitchenledger_tbl_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantDamageFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('damage_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, null=True)),
                ('reported_by', models.CharField(blank=True, max_length=150, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_records', to='restaurant.restaurantitem')),
            ],
        ),
    ]
