# Generated by Django 5.1.7 on 2026-07-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0043_restaurantdamagefood'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsale',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='restaurantsale',
            name='return_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
