# Generated by Django 5.1.7 on 2026-07-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0044_restaurantsale_paid_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantsale',
            old_name='paid_amount',
            new_name='received_amount',
        ),
        migrations.RemoveField(
            model_name='restaurantsale',
            name='note',
        ),
        migrations.AlterField(
            model_name='restaurantsale',
            name='customer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurantsale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
