# Generated by Django 5.1.7 on 2026-07-31 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0045_rename_paid_amount_restaurantsale_received_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantcustomer'),
        ),
    ]
