# Generated by Django 5.1.7 on 2026-07-31 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0046_alter_restaurantsale_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdamagefood',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_records', to='restaurant.restaurantitemamount'),
        ),
    ]
