# Generated by Django 5.1.7 on 2026-08-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0047_alter_restaurantdamagefood_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsale',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurantsale',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
