# Generated by Django 5.1.7 on 2026-08-03 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0048_restaurantsale_note_restaurantsale_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantkitchenledger',
            name='vendor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantjewelsupplier'),
        ),
        migrations.AlterField(
            model_name='restrequisition',
            name='vendor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantjewelsupplier'),
        ),
    ]
