# Generated by Django 5.1.7 on 2026-08-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0049_restaurantkitchenledger_vendor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantitem',
            name='rest_item_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
