# Generated by Django 5.1.7 on 2026-08-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0050_restaurantitem_rest_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantitem',
            name='rest_item_id',
        ),
        migrations.AlterField(
            model_name='restaurantitem',
            name='rest_item_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
