# Generated by Django 5.1.7 on 2025-05-20 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrm', '0008_alter_employee_emp_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requi_id', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(max_length=100)),
                ('qty', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('approv_note', models.TextField(blank=True, null=True)),
                ('approv_acct_note', models.TextField(blank=True, null=True)),
                ('approv_purch_note', models.TextField(blank=True, null=True)),
                ('requisition_date', models.DateField(blank=True, null=True)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.employee')),
            ],
        ),
    ]
