# Generated by Django 5.1.7 on 2025-05-20 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventories', '0001_initial'),
        ('projects', '0017_projectfirstlevelname_location'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventories',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.headofrequisition'),
        ),
        migrations.AddField(
            model_name='inventories',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname'),
        ),
        migrations.AddField(
            model_name='inventories',
            name='vendor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.suppliers'),
        ),
    ]
