# Generated by Django 5.1.7 on 2025-06-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventories',
            name='qtysub',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
