# Generated by Django 5.1.7 on 2025-06-13 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_inventories_qtysub'),
        ('projects', '0017_projectfirstlevelname_location'),
        ('purchase', '0014_remove_expensevoucher_requi_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('details', models.TextField(blank=True, null=True)),
                ('use_date', models.DateField(auto_now_add=True)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.headofrequisition')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname')),
            ],
        ),
    ]
