# Generated by Django 5.1.7 on 2025-06-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0004_inventoryuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryuse',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
