# Generated by Django 5.1.7 on 2025-06-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0005_inventoryuse_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventories',
            name='purch_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
