# Generated by Django 4.2.20 on 2025-06-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0006_inventories_purch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventories',
            name='purch_file',
            field=models.FileField(blank=True, null=True, upload_to='purchase_docs/'),
        ),
    ]
