# Generated by Django 4.2.20 on 2025-06-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0007_inventories_purch_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventories',
            name='purch_file',
            field=models.ImageField(blank=True, null=True, upload_to='purchase_docs/'),
        ),
    ]
