# Generated by Django 4.2.20 on 2025-06-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0008_alter_inventories_purch_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventories',
            name='purch_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
