# Generated by Django 4.2.20 on 2025-07-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0010_deletedrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventories',
            name='purch_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
