# Generated by Django 4.2.20 on 2025-07-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0011_alter_inventories_purch_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventories',
            name='purch_file',
            field=models.ImageField(blank=True, null=True, upload_to='purchase_docs/'),
        ),
    ]
