# Generated by Django 4.2.20 on 2025-07-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0012_alter_inventories_purch_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventories',
            old_name='purch_file',
            new_name='purch_file_1',
        ),
        migrations.AddField(
            model_name='inventories',
            name='purch_file_2',
            field=models.ImageField(blank=True, null=True, upload_to='purchase_docs/'),
        ),
        migrations.AddField(
            model_name='inventories',
            name='purch_file_3',
            field=models.ImageField(blank=True, null=True, upload_to='purchase_docs/'),
        ),
    ]
