# Generated by Django 4.2.20 on 2025-07-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0013_rename_purch_file_inventories_purch_file_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryuse',
            name='qtysub_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryuse',
            name='total_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
