# Generated by Django 4.2.20 on 2025-07-30 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0014_inventoryuse_qtysub_qty_inventoryuse_total_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryuse',
            name='use_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
