# Generated by Django 5.1.7 on 2026-01-28 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_bulksms_recipients_bulksmsrecipient'),
        ('projects', '0031_remove_donation_donation_type'),
        ('restaccounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestCapitalAccount',
            new_name='CapitalRestAccount',
        ),
        migrations.RenameModel(
            old_name='RestCreditVoucher',
            new_name='CreditRestVoucher',
        ),
    ]
