# Generated by Django 5.1.7 on 2026-01-28 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0002_rename_restcapitalaccount_capitalrestaccount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestCashType',
            new_name='CashRestType',
        ),
    ]
