# Generated by Django 5.1.7 on 2026-01-28 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_remove_donation_donation_type'),
        ('restaccounting', '0003_rename_restcashtype_cashresttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ledger_type', models.CharField(choices=[('sales', 'Sales Ledger'), ('cash', 'Cash / Bank Ledger')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname')),
                ('cash_type', models.ForeignKey(limit_choices_to={'ledger_type': 'cash'}, on_delete=django.db.models.deletion.PROTECT, related_name='collection_cash', to='restaccounting.ledger')),
                ('sales_type', models.ForeignKey(limit_choices_to={'ledger_type': 'sales'}, on_delete=django.db.models.deletion.PROTECT, related_name='collection_sales', to='restaccounting.ledger')),
            ],
        ),
    ]
