# Generated by Django 5.1.7 on 2026-01-28 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0004_ledger_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='sales_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_sales', to='restaccounting.cashresttype'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='cash_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_cash', to='restaccounting.cashresttype'),
        ),
        migrations.DeleteModel(
            name='Ledger',
        ),
    ]
