# Generated by Django 5.1.7 on 2026-01-29 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_remove_donation_donation_type'),
        ('restaccounting', '0005_alter_collection_sales_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('date', 'project', 'sales_type')},
        ),
    ]
