# Generated by Django 5.1.7 on 2026-01-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_remove_donation_donation_type'),
        ('restaccounting', '0006_alter_collection_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('date', 'project', 'sales_type'), name='unique_collection_date_project_sales'),
        ),
    ]
