# Generated by Django 5.1.7 on 2026-01-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0007_alter_collection_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_type_name', models.CharField(max_length=100)),
                ('type_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('type_note', models.CharField(default='', max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
