# Generated by Django 5.1.7 on 2026-01-29 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0008_salesresttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='sales_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_sales', to='restaccounting.salesresttype'),
        ),
    ]
