# Generated by Django 5.1.7 on 2026-01-29 17:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_bulksms_recipients_bulksmsrecipient'),
        ('projects', '0031_remove_donation_donation_type'),
        ('purchase', '0056_alter_notification_created_at'),
        ('restaccounting', '0010_debitrestvoucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerRestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor'), ('Customer', 'Customer'), ('Bank', 'Bank'), ('Expense', 'Expense'), ('Capital', 'Capital'), ('Revenue', 'Revenue'), ('Investment', 'Investment'), ('Employee', 'Employee'), ('Balance_Trf', 'Balance_Trf')], default='', max_length=20)),
                ('empl_name', models.CharField(blank=True, max_length=100, null=True)),
                ('balance_trf', models.CharField(blank=True, max_length=100, null=True)),
                ('type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('mr_or_bill_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('carrier', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_status', models.CharField(blank=True, max_length=255, null=True)),
                ('tbl_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tbl_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bankName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_vouchers_as_bank', to='restaccounting.cashresttype')),
                ('capi_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_capital_vr', to='restaccounting.capitalrestaccount')),
                ('cash_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_vouchers_as_cash', to='restaccounting.cashresttype')),
                ('contructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.sitesupervisor')),
                ('customer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer')),
                ('exp_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.headofexpense')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaccounting.restheadofaccount')),
                ('invest_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_invest_vr', to='restaccounting.capitalrestaccount')),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfirstlevelname')),
                ('reve_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_revenue_vr', to='restaccounting.capitalrestaccount')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='RestTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.CharField(blank=True, max_length=255, null=True)),
                ('particulars', models.TextField(blank=True, null=True)),
                ('tbl_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tbl_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cash_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaccounting.cashresttype')),
                ('head_of_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaccounting.restheadofaccount')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname')),
            ],
        ),
    ]
