# Generated by Django 5.1.7 on 2026-01-29 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_bulksms_recipients_bulksmsrecipient'),
        ('projects', '0031_remove_donation_donation_type'),
        ('purchase', '0056_alter_notification_created_at'),
        ('restaccounting', '0011_ledgerrestentry_resttransactionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestLoanVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100)),
                ('empl_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mr_or_bill_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('particulars', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('carrier', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_status', models.CharField(blank=True, max_length=255, null=True)),
                ('bankName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_vouchers_as_bank', to='restaccounting.cashresttype')),
                ('cash_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_vouchers_as_cash', to='restaccounting.cashresttype')),
                ('conductor_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.sitesupervisor')),
                ('customer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer')),
                ('expense_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rest_Loan_voucher_dn', to='purchase.headofexpense')),
                ('headAcct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaccounting.restheadofaccount')),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfirstlevelname')),
                ('source_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rest_Loan_voucher_sn', to='purchase.headofexpense')),
                ('vendor_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.suppliers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
