# Generated by Django 5.1.7 on 2026-01-30 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_remove_donation_donation_type'),
        ('restaccounting', '0012_restloanvoucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_payment_cash', to='restaccounting.cashresttype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname')),
                ('sales_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_payment_sales', to='restaccounting.salesresttype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date', 'project', 'sales_type'), name='unique_dailypayment_date_project_sales')],
            },
        ),
    ]
