# Generated by Django 5.1.7 on 2026-01-31 17:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_remove_donation_donation_type'),
        ('restaccounting', '0013_dailypayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestBalanceTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('carrier', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_transfers_in', to='restaccounting.cashresttype')),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfirstlevelname')),
                ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_transfers_out', to='restaccounting.cashresttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
