# Generated by Django 5.1.7 on 2026-02-15 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0015_restmainchequebook_restmaincheque'),
        ('restahrm', '0034_alter_restaurantadvancepayment_head_of_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitrestvoucher',
            name='empl_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restahrm.restaurantemployee'),
        ),
    ]
