# Generated by Django 5.1.7 on 2026-02-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0016_alter_debitrestvoucher_empl_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitrestvoucher',
            name='empl_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
