# Generated by Django 5.1.7 on 2026-02-21 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_bulksms_recipients_bulksmsrecipient'),
        ('projects', '0031_remove_donation_donation_type'),
        ('restaccounting', '0017_alter_debitrestvoucher_empl_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestFoodBillVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor'), ('Expense', 'Expense'), ('Employee', 'Employee'), ('Customer', 'Customer'), ('Capital', 'Capital'), ('Revenue', 'Revenue'), ('Investment', 'Investment')], max_length=20)),
                ('expense', models.CharField(blank=True, max_length=100, null=True)),
                ('empl_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_phase', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mr_or_bill_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date', models.DateField()),
                ('particulars', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('advance_pay', models.BooleanField(default=False)),
                ('approval_dr_status', models.BooleanField(blank=True, null=True)),
                ('requi_id', models.IntegerField(blank=True, null=True)),
                ('return_requisition', models.CharField(blank=True, max_length=100, null=True)),
                ('carrier', models.CharField(blank=True, max_length=255, null=True)),
                ('create_dr', models.CharField(blank=True, max_length=255, null=True)),
                ('capi_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rest_foodbill_captal_vr', to='restaccounting.capitalrestaccount')),
                ('cash_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaccounting.cashresttype')),
                ('contructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.sitesupervisor')),
                ('customer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer')),
                ('head_of_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaccounting.restheadofaccount')),
                ('invest_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rest_foodbill_invest_vr', to='restaccounting.capitalrestaccount')),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfirstlevelname')),
                ('reve_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rest_foodbill_reve_vr', to='restaccounting.capitalrestaccount')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.suppliers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
