# Generated by Django 5.1.7 on 2026-02-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0018_restfoodbillvoucher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestFoodBillVoucher',
        ),
    ]
