# Generated by Django 5.1.7 on 2026-02-23 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_bulksms_recipients_bulksmsrecipient'),
        ('restaccounting', '0019_delete_restfoodbillvoucher'),
        ('restahrm', '0043_alter_restaurantfoodbillpayment_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer'),
        ),
        migrations.AddField(
            model_name='collection',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restahrm.restaurantemployee'),
        ),
        migrations.AddField(
            model_name='collection',
            name='type',
            field=models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Employee', 'Employee')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dailypayment',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer'),
        ),
        migrations.AddField(
            model_name='dailypayment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restahrm.restaurantemployee'),
        ),
        migrations.AddField(
            model_name='dailypayment',
            name='type',
            field=models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Employee', 'Employee')], max_length=20, null=True),
        ),
    ]
