# Generated by Django 5.1.7 on 2026-02-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0020_collection_customer_name_collection_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrestvoucher',
            name='reqs_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
