# Generated by Django 5.1.7 on 2026-02-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0021_creditrestvoucher_reqs_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collection',
            name='unique_collection_date_project_sales',
        ),
    ]
