# Generated by Django 5.1.7 on 2026-02-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0022_remove_collection_unique_collection_date_project_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='project',
            field=models.CharField(choices=[('galleria_restauent_cafe', 'The Galleria Restauent Cafe'), ('galleria_live_kitchen', 'The Galleria Live Kitchen')], max_length=50),
        ),
    ]
