# Generated by Django 5.1.7 on 2026-02-24 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_remove_donation_donation_type'),
        ('restaccounting', '0023_alter_collection_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname'),
        ),
    ]
