# Generated by Django 5.1.7 on 2026-02-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0024_alter_collection_project'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailypayment',
            name='unique_dailypayment_date_project_sales',
        ),
    ]
