# Generated by Django 5.1.7 on 2026-03-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0025_remove_dailypayment_unique_dailypayment_date_project_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrestvoucher',
            name='res_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
