# Generated by Django 5.1.7 on 2026-03-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0026_creditrestvoucher_res_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerrestentry',
            name='entry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
