# Generated by Django 5.1.7 on 2026-03-11 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0027_ledgerrestentry_entry_date'),
        ('restaurant', '0005_restaurantsupplier_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerrestentry',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.restaurantsupplier'),
        ),
        migrations.AlterField(
            model_name='restloanvoucher',
            name='vendor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.restaurantsupplier'),
        ),
    ]
