# Generated by Django 5.1.7 on 2026-03-13 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0028_alter_ledgerrestentry_vendor_and_more'),
        ('restaurant', '0008_restpurchasecost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailypayment',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='dailypayment',
            name='employee',
        ),
        migrations.AddField(
            model_name='dailypayment',
            name='pur_cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.restpurchasecost'),
        ),
        migrations.AddField(
            model_name='dailypayment',
            name='rest_exp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restexpense'),
        ),
    ]
