# Generated by Django 5.1.7 on 2026-03-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0029_remove_dailypayment_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypayment',
            name='type',
            field=models.CharField(blank=True, choices=[('Expense', 'Expense'), ('Purchase', 'Purchase')], max_length=20, null=True),
        ),
    ]
