# Generated by Django 5.1.7 on 2026-03-13 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0030_alter_dailypayment_type'),
        ('restaurant', '0008_restpurchasecost'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitrestvoucher',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restpurchasecost'),
        ),
        migrations.AlterField(
            model_name='debitrestvoucher',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restexpense'),
        ),
    ]
