# Generated by Django 5.1.7 on 2026-03-13 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0059_alter_requisition_description'),
        ('restaccounting', '0032_ledgerrestentry_purchase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgerrestentry',
            name='purchase',
        ),
        migrations.AlterField(
            model_name='ledgerrestentry',
            name='exp_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.headofexpense'),
        ),
    ]
