# Generated by Django 5.1.7 on 2026-03-13 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0033_remove_ledgerrestentry_purchase_and_more'),
        ('restaurant', '0008_restpurchasecost'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerrestentry',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restpurchasecost'),
        ),
        migrations.AlterField(
            model_name='ledgerrestentry',
            name='exp_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.restexpense'),
        ),
    ]
