# Generated by Django 5.1.7 on 2026-03-25 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0034_ledgerrestentry_purchase_and_more'),
        ('restaurant', '0008_restpurchasecost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restloanvoucher',
            name='expense_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rest_Loan_voucher_dn', to='restaurant.restexpense'),
        ),
        migrations.AlterField(
            model_name='restloanvoucher',
            name='source_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rest_Loan_voucher_sn', to='restaurant.restexpense'),
        ),
    ]
