# Generated by Django 5.1.7 on 2026-03-25 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0035_alter_restloanvoucher_expense_name_and_more'),
        ('restaurant', '0008_restpurchasecost'),
    ]

    operations = [
        migrations.AddField(
            model_name='restloanvoucher',
            name='purchase_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.restpurchasecost'),
        ),
    ]
