# Generated by Django 5.1.7 on 2026-03-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0036_restloanvoucher_purchase_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerrestentry',
            name='type',
            field=models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor'), ('Customer', 'Customer'), ('Bank', 'Bank'), ('Expense', 'Expense'), ('Purchase', 'Purchase'), ('Capital', 'Capital'), ('Revenue', 'Revenue'), ('Investment', 'Investment'), ('Employee', 'Employee'), ('Balance_Trf', 'Balance_Trf')], default='', max_length=20),
        ),
    ]
