# Generated by Django 5.1.7 on 2026-03-28 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0037_alter_ledgerrestentry_type'),
        ('restaurant', '0009_restexpenserequisition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrestvoucher',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.restaurantsupplier'),
        ),
        migrations.AlterField(
            model_name='debitrestvoucher',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.restaurantsupplier'),
        ),
    ]
