# Generated by Django 5.1.7 on 2026-04-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0038_alter_creditrestvoucher_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitrestvoucher',
            name='type',
            field=models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor'), ('Expense', 'Expense'), ('Employee', 'Employee'), ('Customer', 'Customer'), ('Capital', 'Capital'), ('Revenue', 'Revenue'), ('Investment', 'Investment'), ('Purchase', 'Purchase')], max_length=20),
        ),
    ]
