# Generated by Django 5.1.7 on 2026-05-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0039_alter_debitrestvoucher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='cret_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
