# Generated by Django 5.1.7 on 2026-05-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaccounting', '0040_collection_cret_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypayment',
            name='pay_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
