# Generated by Django 5.1.7 on 2025-05-20 07:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0017_projectfirstlevelname_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_name', models.CharField(max_length=100)),
                ('type_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('type_note', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DebitVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor')], max_length=20)),
                ('bill_phase', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mr_or_bill_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('particulars', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('approval_dr_status', models.BooleanField(blank=True, null=True)),
                ('requi_id', models.IntegerField(blank=True, null=True)),
                ('return_requisition', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeadOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head_name', models.CharField(max_length=255)),
                ('head_code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JournalVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100)),
                ('bill_phase', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('amount_dr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_cr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mr_or_bill_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('destination_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='accounting.cashtype')),
                ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='accounting.cashtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContraVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Dr', 'Dr'), ('Cr', 'Cr')], default='Dr', max_length=20)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfirstlevelname')),
            ],
        ),
        migrations.CreateModel(
            name='CreditVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100)),
                ('others', models.CharField(blank=True, max_length=255, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('mr_or_bill_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('particulars', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('approval_cr_status', models.BooleanField(blank=True, null=True)),
                ('cash_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.cashtype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
