# Generated by Django 5.1.7 on 2025-05-20 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('crm', '0001_initial'),
        ('projects', '0017_projectfirstlevelname_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditvoucher',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer'),
        ),
        migrations.AddField(
            model_name='creditvoucher',
            name='lead_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customerlead'),
        ),
        migrations.AddField(
            model_name='creditvoucher',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfirstlevelname'),
        ),
        migrations.AddField(
            model_name='debitvoucher',
            name='cash_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.cashtype'),
        ),
        migrations.AddField(
            model_name='debitvoucher',
            name='contructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.sitesupervisor'),
        ),
        migrations.AddField(
            model_name='debitvoucher',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfirstlevelname'),
        ),
        migrations.AddField(
            model_name='debitvoucher',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.suppliers'),
        ),
        migrations.AddField(
            model_name='debitvoucher',
            name='head_of_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.headofaccount'),
        ),
        migrations.AddField(
            model_name='creditvoucher',
            name='head_of_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.headofaccount'),
        ),
        migrations.AddField(
            model_name='contravoucher',
            name='head_of_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.headofaccount'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='contructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.sitesupervisor'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='head_of_account_cr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_head_cr', to='accounting.headofaccount'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='head_of_account_dr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_head_dr', to='accounting.headofaccount'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='project_cr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_project_cr', to='projects.projectfirstlevelname'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='project_dr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_project_dr', to='projects.projectfirstlevelname'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.suppliers'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.headofaccount'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfirstlevelname'),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='cash_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.cashtype'),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='head_of_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.headofaccount'),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname'),
        ),
    ]
