# Generated by Django 5.1.7 on 2025-05-23 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_loanvoucher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanvoucher',
            old_name='others',
            new_name='carrier',
        ),
        migrations.RemoveField(
            model_name='loanvoucher',
            name='lead_name',
        ),
        migrations.AddField(
            model_name='loanvoucher',
            name='bankName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_vouchers_as_bank', to='accounting.cashtype'),
        ),
        migrations.AlterField(
            model_name='loanvoucher',
            name='cash_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_vouchers_as_cash', to='accounting.cashtype'),
        ),
    ]
