# Generated by Django 5.1.7 on 2025-05-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_rename_others_loanvoucher_carrier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanvoucher',
            name='approval_cr_status',
        ),
        migrations.AddField(
            model_name='cashtype',
            name='bankValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanvoucher',
            name='loan_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
