# Generated by Django 5.1.7 on 2025-05-23 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_remove_loanvoucher_approval_cr_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashtype',
            name='bankValue',
        ),
    ]
