# Generated by Django 5.1.7 on 2025-05-24 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_remove_cashtype_bankvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='carrier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='cash_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.cashtype'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='loan_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='mr_or_bill_no',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
