# Generated by Django 5.1.7 on 2025-05-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_ledgerentry_carrier_ledgerentry_cash_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditvoucher',
            name='carrier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='debitvoucher',
            name='carrier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='carrier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
