# Generated by Django 5.1.7 on 2025-05-24 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_creditvoucher_carrier_debitvoucher_carrier_and_more'),
        ('crm', '0001_initial'),
        ('projects', '0017_projectfirstlevelname_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenBlanceVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor'), ('Customer', 'Customer'), ('Bank', 'Bank')], max_length=20)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mr_or_bill_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('particulars', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('carrier', models.CharField(blank=True, max_length=255, null=True)),
                ('bankName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_blance_vouchers_as_bank', to='accounting.cashtype')),
                ('cash_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_blance_vouchers_as_cash', to='accounting.cashtype')),
                ('contructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.sitesupervisor')),
                ('customer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer')),
                ('head_of_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.headofaccount')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.suppliers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
