# Generated by Django 5.1.7 on 2025-05-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_openblancevoucher_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='ledge_types',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='types_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
