# Generated by Django 5.1.7 on 2025-05-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_ledgerentry_ledge_types_ledgerentry_types_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='ledge_types',
            field=models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor'), ('Customer', 'Customer'), ('Bank', 'Bank')], max_length=20),
        ),
    ]
