# Generated by Django 5.1.7 on 2025-05-24 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_alter_ledgerentry_ledge_types'),
        ('crm', '0001_initial'),
        ('projects', '0017_projectfirstlevelname_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledgerentry',
            old_name='ledge_types',
            new_name='type',
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='bankName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LedgerEntry_vouchers_as_bank', to='accounting.cashtype'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='contructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.sitesupervisor'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.suppliers'),
        ),
    ]
