# Generated by Django 5.1.7 on 2025-05-24 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_rename_ledge_types_ledgerentry_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='cash_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LedgerEntry_vouchers_as_cash', to='accounting.cashtype'),
        ),
    ]
