# Generated by Django 5.1.7 on 2025-05-24 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_alter_ledgerentry_cash_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgerentry',
            name='mr_or_bill_no',
        ),
    ]
