# Generated by Django 5.1.7 on 2025-05-24 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_remove_ledgerentry_mr_or_bill_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgerentry',
            name='types_name',
        ),
    ]
