# Generated by Django 5.1.7 on 2025-05-24 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_remove_ledgerentry_types_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgerentry',
            name='bankName',
        ),
        migrations.RemoveField(
            model_name='ledgerentry',
            name='contructor',
        ),
        migrations.RemoveField(
            model_name='ledgerentry',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='ledgerentry',
            name='type',
        ),
        migrations.RemoveField(
            model_name='ledgerentry',
            name='vendor',
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='mr_or_bill_no',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='cash_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.cashtype'),
        ),
    ]
