# Generated by Django 5.1.7 on 2025-05-24 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_remove_ledgerentry_bankname_and_more'),
        ('crm', '0001_initial'),
        ('projects', '0017_projectfirstlevelname_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgerentry',
            name='mr_or_bill_no',
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='bankName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_vouchers_as_bank', to='accounting.cashtype'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='contructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.sitesupervisor'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='type',
            field=models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor'), ('Customer', 'Customer'), ('Bank', 'Bank')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.suppliers'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='cash_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_vouchers_as_cash', to='accounting.cashtype'),
        ),
    ]
