# Generated by Django 5.1.7 on 2025-05-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_remove_ledgerentry_mr_or_bill_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='type_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
