# Generated by Django 5.1.7 on 2025-05-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_ledgerentry_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='ledger_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
