# Generated by Django 5.1.7 on 2025-05-24 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_ledgerentry_ledger_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgerentry',
            name='ledger_name',
        ),
    ]
