# Generated by Django 5.1.7 on 2025-05-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_remove_ledgerentry_ledger_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='type_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
