# Generated by Django 5.1.7 on 2025-05-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_transactionhistory_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headofaccount',
            name='head_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
