# Generated by Django 5.1.7 on 2025-05-26 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_alter_headofaccount_head_code'),
        ('projects', '0017_projectfirstlevelname_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancetransfer',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfirstlevelname'),
        ),
    ]
