# Generated by Django 5.1.7 on 2025-05-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_balancetransfer_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancetransfer',
            name='carrier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='balancetransfer',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='creditvoucher',
            name='mr_or_bill_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='debitvoucher',
            name='mr_or_bill_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
