# Generated by Django 5.1.7 on 2025-05-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_balancetransfer_carrier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditvoucher',
            name='bill_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
