# Generated by Django 5.1.7 on 2025-05-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_creditvoucher_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitvoucher',
            name='expense',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='debitvoucher',
            name='type',
            field=models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor'), ('Expense', 'Expense')], max_length=20),
        ),
    ]
