# Generated by Django 5.1.7 on 2025-05-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_debitvoucher_expense_alter_debitvoucher_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitvoucher',
            name='type',
            field=models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor')], max_length=20),
        ),
    ]
