# Generated by Django 5.1.7 on 2025-05-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_alter_debitvoucher_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='type',
            field=models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor'), ('Customer', 'Customer'), ('Bank', 'Bank'), ('Expense', 'Expense')], default='', max_length=20),
        ),
    ]
