# Generated by Django 5.1.7 on 2025-05-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_alter_ledgerentry_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashtype',
            old_name='type_name',
            new_name='cash_type_name',
        ),
    ]
