# Generated by Django 5.1.7 on 2025-06-15 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_rename_type_name_cashtype_cash_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('matched', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.cashtype')),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_matches', to='accounting.ledgerentry')),
            ],
        ),
        migrations.CreateModel(
            name='AccountReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_on', models.DateTimeField(auto_now_add=True)),
                ('reconciled_by', models.CharField(blank=True, max_length=150)),
                ('note', models.TextField(blank=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.cashtype')),
                ('ledger_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.ledgerentry')),
                ('statement_txn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.bankstatementtransaction')),
            ],
            options={
                'unique_together': {('bank_account', 'ledger_entry', 'statement_txn')},
            },
        ),
    ]
