# Generated by Django 5.1.7 on 2025-06-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_bankstatementtransaction_accountreconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtype',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
