# Generated by Django 5.1.7 on 2025-06-18 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_cashtype_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalvoucher',
            name='cash_type_cr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='journalvoucher_credit', to='accounting.cashtype'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='cash_type_dr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='journalvoucher_debit', to='accounting.cashtype'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='cheque_number_cr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='cheque_number_dr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
