# Generated by Django 4.2.20 on 2025-06-24 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0016_requisition_requi_uniq_id'),
        ('projects', '0017_projectfirstlevelname_location'),
        ('accounting', '0034_journalvoucher_cash_type_cr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanvoucher',
            name='bankName',
        ),
        migrations.RemoveField(
            model_name='loanvoucher',
            name='cash_type',
        ),
        migrations.RemoveField(
            model_name='loanvoucher',
            name='cheque_number',
        ),
        migrations.RemoveField(
            model_name='loanvoucher',
            name='head_of_account',
        ),
        migrations.AddField(
            model_name='loanvoucher',
            name='conductor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.sitesupervisor'),
        ),
        migrations.AddField(
            model_name='loanvoucher',
            name='expense_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.headofexpense'),
        ),
    ]
