# Generated by Django 4.2.20 on 2025-06-25 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_remove_loanvoucher_bankname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='capital_images/')),
                ('head_of_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.headofaccount')),
            ],
        ),
    ]
