# Generated by Django 4.2.20 on 2025-06-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_capitalaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditvoucher',
            name='create_cr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='debitvoucher',
            name='create_dr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
