# Generated by Django 4.2.20 on 2025-06-28 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_creditvoucher_create_cr_debitvoucher_create_dr'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditvoucher',
            name='capi_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.capitalaccount'),
        ),
    ]
