# Generated by Django 4.2.20 on 2025-06-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_creditvoucher_capi_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditvoucher',
            name='approval_cr_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='debitvoucher',
            name='approval_dr_status',
            field=models.BooleanField(default=False),
        ),
    ]
