# Generated by Django 4.2.20 on 2025-07-01 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_boqtype_boq_type_name'),
        ('accounting', '0039_alter_creditvoucher_approval_cr_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanvoucher',
            name='headAcct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.headofaccount'),
        ),
        migrations.AddField(
            model_name='loanvoucher',
            name='vendor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.suppliers'),
        ),
    ]
