# Generated by Django 4.2.20 on 2025-07-05 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0040_loanvoucher_headacct_loanvoucher_vendor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='capi_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.capitalaccount'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='type',
            field=models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor'), ('Customer', 'Customer'), ('Bank', 'Bank'), ('Expense', 'Expense'), ('Capital', 'Capital'), ('Investment', 'Investment')], default='', max_length=20),
        ),
    ]
