# Generated by Django 4.2.20 on 2025-07-05 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0022_requisition_purch_id'),
        ('accounting', '0041_ledgerentry_capi_name_alter_ledgerentry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='exp_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.headofexpense'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='bankName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_vouchers_as_bank', to='accounting.cashtype'),
        ),
    ]
