# Generated by Django 4.2.20 on 2025-07-07 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0042_ledgerentry_exp_name_alter_ledgerentry_bankname'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanvoucher',
            name='bankName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.cashtype'),
        ),
    ]
