# Generated by Django 4.2.20 on 2025-07-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0043_loanvoucher_bankname'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='empl_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
