# Generated by Django 4.2.20 on 2025-07-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0044_ledgerentry_empl_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='type',
            field=models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor'), ('Customer', 'Customer'), ('Bank', 'Bank'), ('Expense', 'Expense'), ('Capital', 'Capital'), ('Investment', 'Investment'), ('Employee', 'Employee')], default='', max_length=20),
        ),
    ]
