# Generated by Django 4.2.20 on 2025-07-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0045_alter_ledgerentry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitvoucher',
            name='empl_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
