# Generated by Django 4.2.20 on 2025-07-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0046_debitvoucher_empl_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debitvoucher',
            name='empl_name',
        ),
        migrations.AlterField(
            model_name='debitvoucher',
            name='type',
            field=models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor'), ('Employee', 'Employee')], max_length=20),
        ),
    ]
