# Generated by Django 4.2.20 on 2025-07-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0047_remove_debitvoucher_empl_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitvoucher',
            name='empl_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='debitvoucher',
            name='type',
            field=models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor'), ('Employee', 'Employee'), ('Employee', 'Employee')], max_length=20),
        ),
    ]
