# Generated by Django 4.2.20 on 2025-07-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0048_debitvoucher_empl_name_alter_debitvoucher_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitvoucher',
            name='approval_dr_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debitvoucher',
            name='type',
            field=models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor'), ('Expense', 'Expense'), ('Employee', 'Employee')], max_length=20),
        ),
    ]
