# Generated by Django 4.2.20 on 2025-07-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0049_alter_debitvoucher_approval_dr_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='balance_trf',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='type',
            field=models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor'), ('Customer', 'Customer'), ('Bank', 'Bank'), ('Expense', 'Expense'), ('Capital', 'Capital'), ('Investment', 'Investment'), ('Employee', 'Employee'), ('Balance_Trf', 'Balance_Trf')], default='', max_length=20),
        ),
    ]
