# Generated by Django 4.2.20 on 2025-07-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0050_ledgerentry_balance_trf_alter_ledgerentry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetransfer',
            name='cheque_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
