# Generated by Django 4.2.20 on 2025-07-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0051_alter_balancetransfer_cheque_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openblancevoucher',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='openblancevoucher',
            name='cash_type',
        ),
        migrations.RemoveField(
            model_name='openblancevoucher',
            name='cheque_number',
        ),
        migrations.RemoveField(
            model_name='openblancevoucher',
            name='mr_or_bill_no',
        ),
    ]
