# Generated by Django 4.2.20 on 2025-07-15 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0052_remove_openblancevoucher_carrier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openblancevoucher',
            name='cash_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.cashtype'),
        ),
    ]
