# Generated by Django 4.2.20 on 2025-07-16 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0053_openblancevoucher_cash_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanvoucher',
            name='cash_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_vouchers_as_cash', to='accounting.cashtype'),
        ),
        migrations.AlterField(
            model_name='loanvoucher',
            name='bankName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_vouchers_as_bank', to='accounting.cashtype'),
        ),
    ]
