# Generated by Django 4.2.20 on 2025-07-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0054_loanvoucher_cash_type_alter_loanvoucher_bankname'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='mr_or_bill_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
