# Generated by Django 4.2.20 on 2025-07-19 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0055_ledgerentry_mr_or_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitvoucher',
            name='capi_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_captal_vr', to='accounting.capitalaccount'),
        ),
        migrations.AddField(
            model_name='debitvoucher',
            name='invest_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_invest_vr', to='accounting.capitalaccount'),
        ),
        migrations.AlterField(
            model_name='debitvoucher',
            name='type',
            field=models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor'), ('Expense', 'Expense'), ('Employee', 'Employee'), ('Capital', 'Capital'), ('Investment', 'Investment')], max_length=20),
        ),
    ]
