# Generated by Django 4.2.20 on 2025-07-20 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0056_debitvoucher_capi_name_debitvoucher_invest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='invest_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_invest_vr', to='accounting.capitalaccount'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='capi_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_capital_vr', to='accounting.capitalaccount'),
        ),
    ]
