# Generated by Django 4.2.20 on 2025-07-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0057_ledgerentry_invest_name_alter_ledgerentry_capi_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalvoucher',
            old_name='bill_phase',
            new_name='party_combined',
        ),
        migrations.RemoveField(
            model_name='journalvoucher',
            name='amount_cr',
        ),
        migrations.RemoveField(
            model_name='journalvoucher',
            name='bill_date',
        ),
        migrations.RemoveField(
            model_name='journalvoucher',
            name='cash_type_cr',
        ),
        migrations.RemoveField(
            model_name='journalvoucher',
            name='cash_type_dr',
        ),
        migrations.RemoveField(
            model_name='journalvoucher',
            name='cheque_number_cr',
        ),
        migrations.RemoveField(
            model_name='journalvoucher',
            name='contructor',
        ),
        migrations.RemoveField(
            model_name='journalvoucher',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='journalvoucher',
            name='head_of_account_cr',
        ),
        migrations.RemoveField(
            model_name='journalvoucher',
            name='project_cr',
        ),
        migrations.RemoveField(
            model_name='journalvoucher',
            name='type',
        ),
        migrations.RemoveField(
            model_name='journalvoucher',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='journalvoucher',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='journalvoucher',
            name='amount_dr',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='journalvoucher',
            name='carrier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='journalvoucher',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalvoucher',
            name='mr_or_bill_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
