# Generated by Django 4.2.20 on 2025-07-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0058_rename_bill_phase_journalvoucher_party_combined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalvoucher',
            old_name='amount_dr',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='journalvoucher',
            old_name='cheque_number_dr',
            new_name='cheque_number',
        ),
        migrations.RenameField(
            model_name='journalvoucher',
            old_name='head_of_account_dr',
            new_name='head_of_account',
        ),
        migrations.RenameField(
            model_name='journalvoucher',
            old_name='project_dr',
            new_name='project',
        ),
    ]
