# Generated by Django 4.2.20 on 2025-07-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0059_rename_amount_dr_journalvoucher_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalvoucher',
            name='cheque_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
