# Generated by Django 4.2.20 on 2025-07-29 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_materialentry'),
        ('accounting', '0061_rename_party_combined_journalvoucher_party_from_combined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalvoucher',
            old_name='party_from_combined',
            new_name='party_combined',
        ),
        migrations.RemoveField(
            model_name='journalvoucher',
            name='head_of_account_from',
        ),
        migrations.RemoveField(
            model_name='journalvoucher',
            name='head_of_account_to',
        ),
        migrations.RemoveField(
            model_name='journalvoucher',
            name='party_to_combined',
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='head_of_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.headofaccount'),
        ),
        migrations.AlterField(
            model_name='journalvoucher',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfirstlevelname'),
        ),
    ]
