# Generated by Django 4.2.20 on 2025-07-29 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_materialentry'),
        ('accounting', '0062_rename_party_from_combined_journalvoucher_party_combined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalvoucher',
            old_name='party_combined',
            new_name='party_from_combined',
        ),
        migrations.RemoveField(
            model_name='journalvoucher',
            name='head_of_account',
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='head_of_account_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_head_from', to='accounting.headofaccount'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='head_of_account_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_head_to', to='accounting.headofaccount'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='party_to_combined',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='journalvoucher',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_project_dr', to='projects.projectfirstlevelname'),
        ),
    ]
