# Generated by Django 4.2.20 on 2025-08-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0063_rename_party_combined_journalvoucher_party_from_combined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='create_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
