# Generated by Django 4.2.20 on 2025-08-06 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0064_transactionhistory_create_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditvoucher',
            name='invest_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditVoucher_invt', to='accounting.capitalaccount'),
        ),
        migrations.AlterField(
            model_name='creditvoucher',
            name='capi_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditVoucher_capt', to='accounting.capitalaccount'),
        ),
    ]
