# Generated by Django 4.2.20 on 2025-08-10 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_sale_sales_discount_alter_sale_balance_due'),
        ('accounting', '0065_creditvoucher_invest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitvoucher',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer'),
        ),
    ]
