# Generated by Django 4.2.20 on 2025-08-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0066_debitvoucher_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitvoucher',
            name='type',
            field=models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor'), ('Expense', 'Expense'), ('Employee', 'Employee'), ('Customer', 'Customer'), ('Capital', 'Capital'), ('Investment', 'Investment')], max_length=20),
        ),
    ]
