# Generated by Django 4.2.20 on 2025-09-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0067_alter_debitvoucher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='tbl_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='tbl_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
