# Generated by Django 4.2.20 on 2025-09-16 11:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0068_ledgerentry_tbl_id_ledgerentry_tbl_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheetHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_name', models.CharField(choices=[('Assets', 'Assets'), ('Liabilities', 'Liabilities'), ('Equity', 'Equity')], max_length=50)),
                ('type_name', models.CharField(choices=[('Current Assets', 'Current Assets'), ('Fixed Assets', 'Fixed Assets'), ('Current Liabilities', 'Current Liabilities'), ('Long Term Liabilities', 'Long Term Liabilities'), ('Equity Capital', 'Equity Capital'), ('Retained Earnings', 'Retained Earnings')], max_length=50)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='Pending', max_length=10)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.balancesheethead')),
            ],
        ),
    ]
