# Generated by Django 4.2.20 on 2025-09-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0069_balancesheethead_balanceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceitem',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
