# Generated by Django 4.2.20 on 2025-09-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0070_alter_balanceitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='type',
            field=models.CharField(choices=[('Contractor', 'Contractor'), ('Vendor', 'Vendor'), ('Customer', 'Customer'), ('Bank', 'Bank'), ('Expense', 'Expense'), ('Capital', 'Capital'), ('Investment', 'Investment'), ('Employee', 'Employee'), ('Balance_Trf', 'Balance_Trf')], default='', max_length=20),
        ),
    ]
