# Generated by Django 4.2.20 on 2025-09-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0072_alter_ledgerentry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='particulars',
            field=models.TextField(blank=True, null=True),
        ),
    ]
