# Generated by Django 4.2.20 on 2025-10-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0073_transactionhistory_particulars'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitvoucher',
            name='advance_pay',
            field=models.BooleanField(default=False),
        ),
    ]
