# Generated by Django 4.2.20 on 2025-10-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0074_debitvoucher_advance_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanvoucher',
            name='empl_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
