# Generated by Django 4.2.20 on 2025-10-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0075_loanvoucher_empl_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
