# Generated by Django 4.2.20 on 2025-10-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0077_chequebook_cheque'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cheque',
            new_name='MainCheque',
        ),
        migrations.RenameModel(
            old_name='ChequeBook',
            new_name='MainChequeBook',
        ),
    ]
