# Generated by Django 4.2.20 on 2025-10-20 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_alter_boq_category_type'),
        ('accounting', '0078_rename_cheque_maincheque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditvoucher',
            name='contructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.sitesupervisor'),
        ),
        migrations.AddField(
            model_name='creditvoucher',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.suppliers'),
        ),
    ]
