# Generated by Django 5.1.7 on 2025-10-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0079_creditvoucher_contructor_creditvoucher_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='type',
            field=models.CharField(choices=[('Contractor', 'Contractor'), ('Vendor', 'Vendor'), ('Customer', 'Customer'), ('Bank', 'Bank'), ('Expense', 'Expense'), ('Capital', 'Capital'), ('Investment', 'Investment'), ('Employee', 'Employee'), ('Balance_Trf', 'Balance_Trf')], default='', max_length=20),
        ),
    ]
