# Generated by Django 5.1.7 on 2025-11-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0081_alter_ledgerentry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditvoucher',
            name='empl_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
