# Generated by Django 5.1.7 on 2025-11-20 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0082_creditvoucher_empl_name'),
        ('purchase', '0056_alter_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanvoucher',
            name='source_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Loan_voucher_sn', to='purchase.headofexpense'),
        ),
        migrations.AlterField(
            model_name='loanvoucher',
            name='expense_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Loan_voucher_dn', to='purchase.headofexpense'),
        ),
    ]
