# Generated by Django 5.1.7 on 2025-12-08 18:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0083_loanvoucher_source_name_and_more'),
        ('projects', '0027_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProfitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('profit_25', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('final_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profit_record', to='projects.projectfirstlevelname')),
            ],
        ),
    ]
