# Generated by Django 5.1.7 on 2025-12-09 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0084_projectprofitrecord'),
        ('projects', '0027_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitvoucher',
            name='donation_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.donation'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='donation_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.donation'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='type',
            field=models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor'), ('Customer', 'Customer'), ('Bank', 'Bank'), ('Expense', 'Expense'), ('Capital', 'Capital'), ('Investment', 'Investment'), ('Employee', 'Employee'), ('Balance_Trf', 'Balance_Trf'), ('Donation', 'Donation')], default='', max_length=20),
        ),
    ]
