# Generated by Django 5.1.7 on 2025-12-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0085_debitvoucher_donation_name_ledgerentry_donation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitvoucher',
            name='type',
            field=models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor'), ('Expense', 'Expense'), ('Employee', 'Employee'), ('Customer', 'Customer'), ('Capital', 'Capital'), ('Donation', 'Donation'), ('Investment', 'Investment')], max_length=20),
        ),
    ]
