# Generated by Django 5.1.7 on 2025-12-10 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0086_alter_debitvoucher_type'),
        ('projects', '0027_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditvoucher',
            name='donation_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.donation'),
        ),
    ]
