# Generated by Django 5.1.7 on 2025-12-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0087_creditvoucher_donation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetransfer',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
