# Generated by Django 5.1.7 on 2025-12-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0088_alter_balancetransfer_cheque_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='tbl_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='tbl_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
