# Generated by Django 5.1.7 on 2025-12-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0089_transactionhistory_tbl_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openblancevoucher',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
