# Generated by Django 5.1.7 on 2026-01-14 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0090_openblancevoucher_cheque_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditvoucher',
            name='reve_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditVoucher_reve', to='accounting.capitalaccount'),
        ),
        migrations.AddField(
            model_name='debitvoucher',
            name='reve_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_reve_vr', to='accounting.capitalaccount'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='reve_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_revenue_vr', to='accounting.capitalaccount'),
        ),
        migrations.AlterField(
            model_name='debitvoucher',
            name='type',
            field=models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor'), ('Expense', 'Expense'), ('Employee', 'Employee'), ('Customer', 'Customer'), ('Capital', 'Capital'), ('Revenue', 'Revenue'), ('Donation', 'Donation'), ('Investment', 'Investment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='type',
            field=models.CharField(choices=[('Contructor', 'Contructor'), ('Vendor', 'Vendor'), ('Customer', 'Customer'), ('Bank', 'Bank'), ('Expense', 'Expense'), ('Capital', 'Capital'), ('Revenue', 'Revenue'), ('Investment', 'Investment'), ('Employee', 'Employee'), ('Balance_Trf', 'Balance_Trf'), ('Donation', 'Donation')], default='', max_length=20),
        ),
    ]
