# Generated by Django 5.1.7 on 2026-02-10 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0091_creditvoucher_reve_name_debitvoucher_reve_name_and_more'),
        ('projects', '0031_remove_donation_donation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceitem',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfirstlevelname'),
        ),
    ]
