# Generated by Django 5.1.7 on 2026-08-09 12:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0092_balanceitem_project_name'),
        ('projects', '0031_remove_donation_donation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBalanceTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('carrier', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_cash_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_transfers_in', to='accounting.cashtype')),
                ('destination_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='projects.projectfirstlevelname')),
                ('source_cash_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_transfers_out', to='accounting.cashtype')),
                ('source_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='projects.projectfirstlevelname')),
            ],
        ),
    ]
