# Generated by Django 5.1.7 on 2026-06-27 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landowner',
            name='relation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Relation'),
        ),
        migrations.AlterField(
            model_name='landowner',
            name='step_label',
            field=models.CharField(blank=True, max_length=200, verbose_name='Step Label'),
        ),
        migrations.CreateModel(
            name='LandOwnerExtraParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_parent_links', to='tracker.landowner')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_child_links', to='tracker.landowner')),
            ],
            options={
                'verbose_name': 'Extra Parent Link',
                'unique_together': {('child', 'parent')},
            },
        ),
    ]
