# Generated by Django 5.1.7 on 2026-06-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_landowner_relation_alter_landowner_step_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landowner',
            name='dagno',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='landowner',
            name='share',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
