# Generated by Django 5.1.7 on 2026-06-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_landowner_dagno_landowner_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landrecord',
            name='land_dag_no',
        ),
        migrations.AddField(
            model_name='landrecord',
            name='cs_dag_no',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='CS Dag No'),
        ),
        migrations.AddField(
            model_name='landrecord',
            name='ct_dag_no',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='CT Dag No'),
        ),
        migrations.AddField(
            model_name='landrecord',
            name='mouza_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Mouza Name'),
        ),
        migrations.AddField(
            model_name='landrecord',
            name='rs_dag_no',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='RS Dag No'),
        ),
        migrations.AddField(
            model_name='landrecord',
            name='sa_dag_no',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='SA Dag No'),
        ),
    ]
