# Generated by Django 5.1.7 on 2026-06-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_landrecord_land_dag_no_landrecord_cs_dag_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrecord',
            name='land_dag_no',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='General Dag No'),
        ),
    ]
