# Generated by Django 5.1.7 on 2025-06-20 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0034_journalvoucher_cash_type_cr_and_more'),
        ('projects', '0017_projectfirstlevelname_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_no', models.CharField(max_length=20)),
                ('unit_no', models.CharField(max_length=20)),
                ('unit_count', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('cash_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.cashtype')),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.headofaccount')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname')),
            ],
        ),
    ]
