# Generated by Django 4.2.20 on 2025-08-09 04:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_sale_sales_discount_alter_sale_balance_due'),
        ('projects', '0024_materialentry'),
        ('sales', '0002_alter_sales_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('flat', 'Flat'), ('plot', 'Plot')], max_length=10)),
                ('flat_no', models.IntegerField()),
                ('unit_no', models.IntegerField()),
                ('property_name', models.CharField(blank=True, max_length=255, null=True)),
                ('property_code', models.CharField(blank=True, max_length=100, null=True)),
                ('square_fit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_square_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('utility', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parking', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sales_date', models.DateField(default=django.utils.timezone.now)),
                ('sales_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('pay_last_status', models.CharField(default='Pending', max_length=20)),
                ('customer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyFlatPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_no', models.IntegerField()),
                ('unit_no', models.IntegerField()),
                ('type', models.CharField(choices=[('flat', 'Flat'), ('plot', 'Plot')], default='flat', max_length=10)),
                ('property_name', models.CharField(blank=True, max_length=255, null=True)),
                ('property_code', models.CharField(blank=True, max_length=100, null=True)),
                ('square_fit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_square_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname')),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(choices=[('booking_money', 'Booking Money'), ('down_payment', 'Down Payment'), ('installment_1', '1st Installment'), ('installment_2', '2nd Installment'), ('installment_3', '3rd Installment'), ('installment_4', '4th Installment'), ('installment_5', '5th Installment'), ('installment_6', '6th Installment')], max_length=50)),
                ('month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cheque_posted', models.BooleanField(default=False)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=100, null=True)),
                ('pay_status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname')),
                ('property_sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.propertysales')),
            ],
        ),
        migrations.CreateModel(
            name='FlatPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_no', models.IntegerField()),
                ('unit_no', models.IntegerField()),
                ('type', models.CharField(choices=[('flat', 'Flat'), ('plot', 'Plot')], default='flat', max_length=10)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname')),
            ],
        ),
    ]
