# Generated by Django 4.2.20 on 2025-08-11 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0067_alter_debitvoucher_type'),
        ('crm', '0005_sale_sales_discount_alter_sale_balance_due'),
        ('sales', '0003_propertysales_propertyflatplot_installmentpayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentpayment',
            name='cash_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.cashtype'),
        ),
        migrations.AddField(
            model_name='installmentpayment',
            name='mr_or_bill_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='propertysales',
            name='commisoin_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='propertysales',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='propertysales',
            name='media_commisoin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='propertysales',
            name='media_persion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PropertySales_media_vr', to='crm.customer'),
        ),
        migrations.AlterField(
            model_name='propertysales',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PropertySales_cus_vr', to='crm.customer'),
        ),
    ]
