# Generated by Django 4.2.20 on 2025-09-18 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_installmentpayment_cash_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharePlot',
            fields=[
                ('sl', models.AutoField(primary_key=True, serialize=False)),
                ('decimal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('share_val', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='SharePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('share_plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='sales.shareplot')),
            ],
        ),
    ]
