# Generated by Django 4.2.20 on 2025-09-18 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_materialentry'),
        ('sales', '0005_shareplot_shareperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareplot',
            name='persion_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shareplot',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname'),
        ),
    ]
