# Generated by Django 4.2.20 on 2025-09-23 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_materialentry'),
        ('crm', '0006_custinfobank'),
        ('accounting', '0070_alter_balanceitem_status'),
        ('sales', '0006_shareplot_persion_no_shareplot_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareInstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(choices=[('booking_money', 'Booking Money'), ('down_payment', 'Down Payment'), ('installment_1', '1st Installment'), ('installment_2', '2nd Installment'), ('installment_3', '3rd Installment'), ('installment_4', '4th Installment'), ('installment_5', '5th Installment'), ('installment_6', '6th Installment')], max_length=50)),
                ('month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cheque_posted', models.BooleanField(default=False)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=100, null=True)),
                ('mr_or_bill_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('pay_status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.cashtype')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectfirstlevelname')),
                ('property_sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.propertysales')),
            ],
        ),
    ]
