# Generated by Django 4.2.20 on 2025-09-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_shareinstallmentpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareplot',
            name='pay_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
