# Generated by Django 4.2.20 on 2025-09-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_shareplot_pay_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareplot',
            name='pay_status',
        ),
        migrations.AddField(
            model_name='shareperson',
            name='pay_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
