# Generated by Django 4.2.20 on 2025-09-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_remove_shareplot_pay_status_shareperson_pay_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareinstallmentpayment',
            name='property_sales',
        ),
        migrations.AddField(
            model_name='shareinstallmentpayment',
            name='share_sales',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.shareplot'),
        ),
        migrations.AlterField(
            model_name='shareinstallmentpayment',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.shareperson'),
        ),
    ]
