# Generated by Django 4.2.20 on 2025-09-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_remove_shareinstallmentpayment_property_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareinstallmentpayment',
            name='payment_type',
            field=models.CharField(choices=[('booking_money', 'Booking Money'), ('down_payment', 'Down Payment'), ('installment_1', '1st Installment'), ('installment_2', '2nd Installment'), ('installment_3', '3rd Installment'), ('installment_4', '4th Installment'), ('installment_5', '5th Installment')], max_length=50),
        ),
    ]
