# Generated by Django 4.2.20 on 2025-10-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_shareinstallmentpayment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareinstallmentpayment',
            name='sl',
            field=models.IntegerField(default=0),
        ),
    ]
