# Generated by Django 4.2.20 on 2025-10-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_shareinstallmentpayment_sl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareinstallmentpayment',
            name='id',
        ),
        migrations.AlterField(
            model_name='shareinstallmentpayment',
            name='sl',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
