# Generated by Django 4.2.20 on 2025-10-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_remove_shareinstallmentpayment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysales',
            name='lilahetalah_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='propertysales',
            name='lilahetalah_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
