# Generated by Django 5.1.7 on 2025-12-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_propertysales_lilahetalah_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentpayment',
            name='pay_note',
            field=models.CharField(default='', max_length=20),
        ),
    ]
