# Generated by Django 5.1.7 on 2025-12-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_installmentpayment_pay_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentpayment',
            name='pay_note',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
