# Generated by Django 5.1.7 on 2025-12-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_installmentpayment_pay_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysales',
            name='donaton_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
