# Generated by Django 5.1.7 on 2025-12-08 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0056_alter_notification_created_at'),
        ('sales', '0017_propertysales_donaton_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertysales',
            name='donaton_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.headofexpense'),
        ),
    ]
