# Generated by Django 5.1.7 on 2026-01-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_alter_propertysales_donaton_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentpayment',
            name='mr_or_bill_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
