# Generated by Django 5.1.7 on 2026-02-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_installmentpayment_mr_or_bill_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentpayment',
            name='payment_type',
            field=models.CharField(choices=[('booking_money', 'Booking Money'), ('down_payment', 'Down Payment'), ('installment_1', '1st Installment'), ('installment_2', '2nd Installment'), ('installment_3', '3rd Installment'), ('installment_4', '4th Installment'), ('installment_5', '5th Installment'), ('installment_6', '6th Installment'), ('installment_7', '7th Installment'), ('installment_8', '8th Installment'), ('installment_9', '9th Installment'), ('installment_10', '10th Installment'), ('installment_11', '11th Installment'), ('installment_12', '12th Installment'), ('installment_13', '13th Installment'), ('installment_14', '14th Installment'), ('installment_15', '15th Installment'), ('installment_16', '16th Installment'), ('installment_17', '17th Installment'), ('installment_18', '18th Installment'), ('installment_19', '19th Installment'), ('installment_20', '20th Installment')], max_length=50),
        ),
    ]
