# Generated by Django 5.1.7 on 2026-02-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_alter_installmentpayment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentpayment',
            name='pay_note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
