# Generated by Django 5.1.7 on 2026-07-23 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_remove_donation_donation_type'),
        ('sales', '0021_alter_installmentpayment_pay_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertysales',
            name='donaton_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.donation'),
        ),
    ]
